CPSC 462 - Asteroids: Asteroids::Domain::Net::Messages::AUTH_ATTEMPT Class Reference
Asteroids::Domain::Net::Messages::AUTH_ATTEMPT Class Reference
Just holds one authentication attempt; Is "sent to server".
#include <AUTH_ATTEMPT.h>
Public Member Functions
AUTH_ATTEMPT ()
void reset ()
void setPassword (string password)
void setUsername (string username)
Static Public Attributes
static constexpr const char * DEFAULT_PASSWORD = ""
static constexpr const char * DEFAULT_USERNAME = ""
Private Attributes
string _password
string _username
Detailed Description
Just holds one authentication attempt; Is "sent to server".
Definition at line 29 of file AUTH_ATTEMPT.h.
Constructor & Destructor Documentation
AUTH_ATTEMPT()
Asteroids::Domain::Net::Messages::AUTH_ATTEMPT::AUTH_ATTEMPT ()
Definition at line 20 of file AUTH_ATTEMPT.cpp.
References reset().
Member Function Documentation
reset()
void Asteroids::Domain::Net::Messages::AUTH_ATTEMPT::reset ()
Definition at line 27 of file AUTH_ATTEMPT.cpp.
References DEFAULT_PASSWORD, DEFAULT_USERNAME, setPassword(), and setUsername().
Referenced by AUTH_ATTEMPT().
setPassword()
void Asteroids::Domain::Net::Messages::AUTH_ATTEMPT::setPassword (string password)
Definition at line 42 of file AUTH_ATTEMPT.cpp.
References _password.
Referenced by reset().
setUsername()
void Asteroids::Domain::Net::Messages::AUTH_ATTEMPT::setUsername (string username)
Definition at line 35 of file AUTH_ATTEMPT.cpp.
References _username.
Referenced by reset().
Member Data Documentation
_password
string Asteroids::Domain::Net::Messages::AUTH_ATTEMPT::_password private
Definition at line 53 of file AUTH_ATTEMPT.h.
Referenced by setPassword().
_username
string Asteroids::Domain::Net::Messages::AUTH_ATTEMPT::_username private
Definition at line 53 of file AUTH_ATTEMPT.h.
Referenced by setUsername().
DEFAULT_PASSWORD
constexpr const char* Asteroids::Domain::Net::Messages::AUTH_ATTEMPT::DEFAULT_PASSWORD = "" static
Definition at line 46 of file AUTH_ATTEMPT.h.
Referenced by reset().
DEFAULT_USERNAME
constexpr const char* Asteroids::Domain::Net::Messages::AUTH_ATTEMPT::DEFAULT_USERNAME = "" static
Definition at line 45 of file AUTH_ATTEMPT.h.
Referenced by reset().
The documentation for this class was generated from the following files:
Domain/Net/Messages/AUTH_ATTEMPT.h
Domain/Net/Messages/AUTH_ATTEMPT.cpp