CPSC 462 - Asteroids: Asteroids::Domain::Game::Actors::GunShip Class Reference
Asteroids::Domain::Game::Actors::GunShip Class Reference
GunShip is the player's main actor; Subclass of Actor; Flies around and shoots at stuff.
#include <GunShip.h>
Public Member Functions
GunShip ()
void reset ()
void update (long ticks)
Public Member Functions inherited from Asteroids::Domain::Game::Actors::Actor
Actor ()
double adjust_rotation (double radians)
bool check_collision (const Asteroids::Domain::Game::Actors::Actor &other_actor)
bool check_collision (std::shared_ptr< Asteroids::Domain::Game::Actors::Actor > other_actor)
void clear_input ()
std::vector< std::shared_ptr< Bullet > > get_fired_bullets (bool clear=true)
long get_lifetime_ticks ()
const std::vector< std::pair< double, double > > & get_polygon ()
std::pair< double, double > get_position ()
Rect get_rect () const
std::vector< std::pair< double, double > > get_rotated_polygon ()
double get_rotation ()
double get_x ()
double get_y ()
void reset ()
std::vector< std::pair< double, double > > rotate_polygon (double radians)
void set_input_down (bool b)
void set_input_fire (bool b)
void set_input_left (bool b)
void set_input_right (bool b)
void set_input_up (bool b)
void set_polygon (std::vector< std::pair< double, double >> points)
void set_position (double x, double y)
double set_rotation (double radians)
void set_velocity (double x, double y, double r)
void update (long elapsed_ticks)
bool wants_to_be_deleted ()
Private Member Functions
void fire_gun ()
void init ()
void initialize_polygon ()
void use_input (long elapsed_ticks)
Additional Inherited Members
Protected Member Functions inherited from Asteroids::Domain::Game::Actors::Actor
void deleteme ()
void fire_bullet ()
void set_bullet_speed (double s)
void update_rect ()
Protected Attributes inherited from Asteroids::Domain::Game::Actors::Actor
bool _input_down
bool _input_fire
bool _input_left
bool _input_right
bool _input_up
std::unique_ptr< Vector > _vector
Detailed Description
GunShip is the player's main actor; Subclass of Actor; Flies around and shoots at stuff.
Definition at line 23 of file GunShip.h.
Constructor & Destructor Documentation
GunShip()
Asteroids::Domain::Game::Actors::GunShip::GunShip ()
Definition at line 22 of file GunShip.cpp.
References init().
Member Function Documentation
fire_gun()
void Asteroids::Domain::Game::Actors::GunShip::fire_gun () private
init()
void Asteroids::Domain::Game::Actors::GunShip::init () private
Definition at line 92 of file GunShip.cpp.
References reset().
Referenced by GunShip().
initialize_polygon()
void Asteroids::Domain::Game::Actors::GunShip::initialize_polygon () private
Definition at line 99 of file GunShip.cpp.
References ASTEROIDS_GAME_ACTOR_SIZE_FACTOR, and Asteroids::Domain::Game::Actors::Actor::set_polygon().
Referenced by reset().
reset()
void Asteroids::Domain::Game::Actors::GunShip::reset ()
Definition at line 29 of file GunShip.cpp.
References ASTEROIDS_GAME_GUNSHIP_BULLET_SPEED, initialize_polygon(), Asteroids::Domain::Game::Actors::Actor::reset(), and Asteroids::Domain::Game::Actors::Actor::set_bullet_speed().
Referenced by init().
update()
void Asteroids::Domain::Game::Actors::GunShip::update (long ticks)
Definition at line 42 of file GunShip.cpp.
References Asteroids::Domain::Game::Actors::Actor::update(), and use_input().
use_input()
void Asteroids::Domain::Game::Actors::GunShip::use_input (long elapsed_ticks) private
Definition at line 52 of file GunShip.cpp.
References Asteroids::Domain::Game::Actors::Actor::_input_down, Asteroids::Domain::Game::Actors::Actor::_input_fire, Asteroids::Domain::Game::Actors::Actor::_input_left, Asteroids::Domain::Game::Actors::Actor::_input_right, Asteroids::Domain::Game::Actors::Actor::_input_up, Asteroids::Domain::Game::Actors::Actor::_vector, ASTEROIDS_GAME_VELOCITY_INPUT_TICKS_FACTOR, Asteroids::Domain::Game::Actors::Actor::fire_bullet(), Asteroids::Domain::Game::Actors::Actor::get_rotation(), Asteroids::Domain::Game::Actors::Vector::rotate_velocity(), and Asteroids::Domain::Game::Actors::Actor::set_input_fire().
Referenced by update().
The documentation for this class was generated from the following files:
Domain/Game/Actors/GunShip.h
Domain/Game/Actors/GunShip.cpp