CPSC 462 - Asteroids: Asteroids::UI::ServerTextUI::ServerTextUI Class Reference
Asteroids::UI::ServerTextUI::ServerTextUI Class Reference
Implementation of ServerTextUIInterface.
#include <ServerTextUI.h>
Public Member Functions
ServerTextUI (std::shared_ptr< Asteroids::Domain::Factory::FactoryInterface > factory)
void run ()
Private Member Functions
void do_apply_updates ()
void do_process_credit_card_payment ()
bool do_review_flagged_user ()
void do_review_flagged_users ()
void init ()
Enums::MainMenuChoice main_menu ()
void main_menu_loop ()
Private Attributes
std::shared_ptr< Asteroids::Domain::Server::ServerDaemonInterface > _daemon
std::shared_ptr< Asteroids::Domain::Factory::FactoryInterface > _factory
std::shared_ptr< Asteroids::Domain::Server::ServerFactoryInterface > _factory_server
std::shared_ptr< Asteroids::TechnicalServices::TechnicalServicesFactoryInterface > _factory_technical_services
Detailed Description
Implementation of ServerTextUIInterface.
Definition at line 27 of file ServerTextUI.h.
Constructor & Destructor Documentation
ServerTextUI()
Asteroids::UI::ServerTextUI::ServerTextUI::ServerTextUI (std::shared_ptr< Asteroids::Domain::Factory::FactoryInterface > factory)
Definition at line 30 of file ServerTextUI.cpp.
References _factory, and init().
Member Function Documentation
do_apply_updates()
void Asteroids::UI::ServerTextUI::ServerTextUI::do_apply_updates () private
Definition at line 195 of file ServerTextUI.cpp.
References _daemon.
Referenced by main_menu_loop().
do_process_credit_card_payment()
void Asteroids::UI::ServerTextUI::ServerTextUI::do_process_credit_card_payment () private
Definition at line 147 of file ServerTextUI.cpp.
References _factory_technical_services, Asteroids::TechnicalServices::Financial::CreditCardProcessorInterface::authorizePayment(), and Asteroids::TechnicalServices::Financial::CreditCardProcessorInterface::get_processor_description().
Referenced by main_menu_loop().
do_review_flagged_user()
bool Asteroids::UI::ServerTextUI::ServerTextUI::do_review_flagged_user () private
Definition at line 218 of file ServerTextUI.cpp.
References _daemon.
Referenced by do_review_flagged_users().
do_review_flagged_users()
void Asteroids::UI::ServerTextUI::ServerTextUI::do_review_flagged_users () private
Definition at line 208 of file ServerTextUI.cpp.
References do_review_flagged_user().
Referenced by main_menu_loop().
init()
void Asteroids::UI::ServerTextUI::ServerTextUI::init () private
Definition at line 136 of file ServerTextUI.cpp.
References _daemon, _factory, _factory_server, and _factory_technical_services.
Referenced by ServerTextUI().
main_menu()
Enums::MainMenuChoice Asteroids::UI::ServerTextUI::ServerTextUI::main_menu () private
Definition at line 93 of file ServerTextUI.cpp.
References _daemon, Asteroids::UI::ServerTextUI::Enums::ApplyUpdates, Asteroids::UI::ServerTextUI::Enums::Invalid, Asteroids::UI::ServerTextUI::Enums::ProcessCreditCardPayment, Asteroids::UI::ServerTextUI::Enums::ReviewFlaggedUsers, and Asteroids::UI::ServerTextUI::Enums::Shutdown.
Referenced by main_menu_loop().
main_menu_loop()
void Asteroids::UI::ServerTextUI::ServerTextUI::main_menu_loop () private
Definition at line 49 of file ServerTextUI.cpp.
References Asteroids::UI::ServerTextUI::Enums::ApplyUpdates, do_apply_updates(), do_process_credit_card_payment(), do_review_flagged_users(), Asteroids::UI::ServerTextUI::Enums::Invalid, main_menu(), Asteroids::UI::ServerTextUI::Enums::ProcessCreditCardPayment, Asteroids::UI::ServerTextUI::Enums::ReviewFlaggedUsers, and Asteroids::UI::ServerTextUI::Enums::Shutdown.
Referenced by run().
run()
void Asteroids::UI::ServerTextUI::ServerTextUI::run () virtual
It is assumed that if you're sitting at the Admin console interface, You already have permission to Administer the server, Since to get to that point you'd need to be able to login to the computer's main server account anyway
Implements Asteroids::UI::ServerTextUI::ServerTextUIInterface.
Definition at line 42 of file ServerTextUI.cpp.
References main_menu_loop().
Member Data Documentation
_daemon
std::shared_ptr<Asteroids::Domain::Server::ServerDaemonInterface> Asteroids::UI::ServerTextUI::ServerTextUI::_daemon private
Definition at line 47 of file ServerTextUI.h.
Referenced by do_apply_updates(), do_review_flagged_user(), init(), and main_menu().
_factory
std::shared_ptr<Asteroids::Domain::Factory::FactoryInterface> Asteroids::UI::ServerTextUI::ServerTextUI::_factory private
Definition at line 43 of file ServerTextUI.h.
Referenced by init(), and ServerTextUI().
_factory_server
std::shared_ptr<Asteroids::Domain::Server::ServerFactoryInterface> Asteroids::UI::ServerTextUI::ServerTextUI::_factory_server private
Definition at line 44 of file ServerTextUI.h.
Referenced by init().
_factory_technical_services
std::shared_ptr<Asteroids::TechnicalServices::TechnicalServicesFactoryInterface> Asteroids::UI::ServerTextUI::ServerTextUI::_factory_technical_services private
Definition at line 45 of file ServerTextUI.h.
Referenced by do_process_credit_card_payment(), and init().
The documentation for this class was generated from the following files:
UI/ServerTextUI/ServerTextUI.h
UI/ServerTextUI/ServerTextUI.cpp