CPSC 462 - Asteroids: Asteroids::Domain::Game::Game Class Reference
Asteroids::Domain::Game::Game Class Reference
Implementation of GameInterface (ie: The game ...)
#include <Game.h>
Public Member Functions
Game ()
std::vector< std::shared_ptr< Asteroids::Domain::Game::Actors::ActorInterface > > get_actors ()
Return all actors in the game.
double get_board_height ()
double get_board_width ()
std::shared_ptr< Asteroids::Domain::Game::Actors::ActorInterface > get_player ()
Return the player.
int get_round ()
int get_score ()
long get_ticks_per_second ()
bool is_active ()
void quit ()
void reset ()
void start ()
void update ()
void wait_for_frames_per_second (long tps)
Implement GameInterface methods.
Private Member Functions
long calculate_ticks_since_last_update (bool update=true)
long get_current_timestamp_ticks ()
Ticks are just microseconds.
std::pair< double, double > get_random_board_position ()
void init ()
void initialize_random_rocks ()
void keep_actors_in_bounds ()
void lose_round ()
void maybe_lose_round ()
void maybe_win_round ()
void randomly_place_player ()
void start_round ()
void win_round ()
Private Attributes
double _board_height
double _board_width
std::vector< std::shared_ptr< Asteroids::Domain::Game::Actors::Bullet > > _bullets
std::unique_ptr< Asteroids::Domain::Factory::Factory > _factory
std::unique_ptr< Asteroids::Domain::Game::GameFactoryInterface > _game_factory
bool _is_active
bool _is_round_active
long _last_time_ms
std::shared_ptr< Actors::GunShip > _player
int _player_score
std::unique_ptr< Randomer > _randomer
std::vector< std::shared_ptr< Asteroids::Domain::Game::Actors::Rock > > _rocks
int _round_number
long _ticks_per_second
Detailed Description
Implementation of GameInterface (ie: The game ...)
Definition at line 25 of file Game.h.
Constructor & Destructor Documentation
Game()
Asteroids::Domain::Game::Game::Game ()
Definition at line 36 of file Game.cpp.
References init().
Member Function Documentation
calculate_ticks_since_last_update()
long Asteroids::Domain::Game::Game::calculate_ticks_since_last_update (bool update = true) private
Definition at line 275 of file Game.cpp.
References _last_time_ms, and get_current_timestamp_ticks().
Referenced by update(), and wait_for_frames_per_second().
get_actors()
std::vector< std::shared_ptr< Asteroids::Domain::Game::Actors::ActorInterface > > Asteroids::Domain::Game::Game::get_actors () virtual
Return all actors in the game.
Implements Asteroids::Domain::Game::GameInterface.
Definition at line 232 of file Game.cpp.
References _bullets, _player, and _rocks.
Referenced by keep_actors_in_bounds().
get_board_height()
double Asteroids::Domain::Game::Game::get_board_height () virtual
Implements Asteroids::Domain::Game::GameInterface.
Definition at line 184 of file Game.cpp.
References _board_height.
get_board_width()
double Asteroids::Domain::Game::Game::get_board_width () virtual
Implements Asteroids::Domain::Game::GameInterface.
Definition at line 177 of file Game.cpp.
References _board_width.
get_current_timestamp_ticks()
long Asteroids::Domain::Game::Game::get_current_timestamp_ticks () private
Ticks are just microseconds.
Definition at line 260 of file Game.cpp.
Referenced by calculate_ticks_since_last_update().
get_player()
std::shared_ptr< Asteroids::Domain::Game::Actors::ActorInterface > Asteroids::Domain::Game::Game::get_player () virtual
Return the player.
Implements Asteroids::Domain::Game::GameInterface.
Definition at line 225 of file Game.cpp.
References _player.
get_random_board_position()
std::pair< double, double > Asteroids::Domain::Game::Game::get_random_board_position () private
Definition at line 250 of file Game.cpp.
References _board_height, _board_width, and _randomer.
Referenced by initialize_random_rocks(), and randomly_place_player().
get_round()
int Asteroids::Domain::Game::Game::get_round () virtual
Implements Asteroids::Domain::Game::GameInterface.
Definition at line 211 of file Game.cpp.
References _round_number.
get_score()
int Asteroids::Domain::Game::Game::get_score () virtual
Implements Asteroids::Domain::Game::GameInterface.
Definition at line 218 of file Game.cpp.
References _player_score.
get_ticks_per_second()
long Asteroids::Domain::Game::Game::get_ticks_per_second ()
Definition at line 191 of file Game.cpp.
References _ticks_per_second.
init()
void Asteroids::Domain::Game::Game::init () private
Definition at line 43 of file Game.cpp.
References _factory, _game_factory, _player, _randomer, and reset().
Referenced by Game().
initialize_random_rocks()
void Asteroids::Domain::Game::Game::initialize_random_rocks () private
Definition at line 298 of file Game.cpp.
References _randomer, _rocks, ASTEROIDS_GAME_ROCKS_INITIAL_VELOCITY_STRENGTH, ASTEROIDS_GAME_ROCKS_PER_LEVEL, and get_random_board_position().
Referenced by start_round().
is_active()
bool Asteroids::Domain::Game::Game::is_active () virtual
Implements Asteroids::Domain::Game::GameInterface.
Definition at line 170 of file Game.cpp.
References _is_active.
keep_actors_in_bounds()
void Asteroids::Domain::Game::Game::keep_actors_in_bounds () private
Definition at line 418 of file Game.cpp.
References _board_height, _board_width, and get_actors().
Referenced by update().
lose_round()
void Asteroids::Domain::Game::Game::lose_round () private
Definition at line 401 of file Game.cpp.
References quit().
Referenced by maybe_lose_round().
maybe_lose_round()
void Asteroids::Domain::Game::Game::maybe_lose_round () private
Definition at line 385 of file Game.cpp.
References _is_active, _is_round_active, _rocks, and lose_round().
Referenced by update().
maybe_win_round()
void Asteroids::Domain::Game::Game::maybe_win_round () private
Definition at line 369 of file Game.cpp.
References _is_active, _is_round_active, _rocks, and win_round().
Referenced by update().
quit()
void Asteroids::Domain::Game::Game::quit () virtual
Implements Asteroids::Domain::Game::GameInterface.
Definition at line 163 of file Game.cpp.
References _is_active.
Referenced by lose_round().
randomly_place_player()
void Asteroids::Domain::Game::Game::randomly_place_player () private
Definition at line 408 of file Game.cpp.
References _player, and get_random_board_position().
Referenced by start().
reset()
void Asteroids::Domain::Game::Game::reset () virtual
Implements Asteroids::Domain::Game::GameInterface.
Definition at line 64 of file Game.cpp.
References _board_height, _board_width, _is_active, _is_round_active, _last_time_ms, _player_score, _round_number, _ticks_per_second, ASTEROIDS_GAME_BOARD_HEIGHT, ASTEROIDS_GAME_BOARD_WIDTH, and ASTEROIDS_GAME_TICKS_PER_SECOND.
Referenced by init().
start()
void Asteroids::Domain::Game::Game::start () virtual
Implements Asteroids::Domain::Game::GameInterface.
Definition at line 82 of file Game.cpp.
References _is_active, _round_number, randomly_place_player(), and start_round().
start_round()
void Asteroids::Domain::Game::Game::start_round () private
Definition at line 358 of file Game.cpp.
References _is_round_active, _round_number, and initialize_random_rocks().
Referenced by start(), and win_round().
update()
void Asteroids::Domain::Game::Game::update () virtual
Todo:
Rocks should eventually split when hit
Implements Asteroids::Domain::Game::GameInterface.
Definition at line 96 of file Game.cpp.
References _bullets, _player, _player_score, _rocks, ASTEROIDS_GAME_ROCKS_POINTS, ASTEROIDS_GAME_TARGET_FRAMES_PER_SECOND, calculate_ticks_since_last_update(), keep_actors_in_bounds(), maybe_lose_round(), maybe_win_round(), and wait_for_frames_per_second().
wait_for_frames_per_second()
void Asteroids::Domain::Game::Game::wait_for_frames_per_second (long tps) virtual
Implement GameInterface methods.
Implements Asteroids::Domain::Game::GameInterface.
Definition at line 198 of file Game.cpp.
References _ticks_per_second, and calculate_ticks_since_last_update().
Referenced by update().
win_round()
void Asteroids::Domain::Game::Game::win_round () private
Definition at line 378 of file Game.cpp.
References start_round().
Referenced by maybe_win_round().
Member Data Documentation
_board_height
double Asteroids::Domain::Game::Game::_board_height private
Definition at line 76 of file Game.h.
Referenced by get_board_height(), get_random_board_position(), keep_actors_in_bounds(), and reset().
_board_width
double Asteroids::Domain::Game::Game::_board_width private
Definition at line 76 of file Game.h.
Referenced by get_board_width(), get_random_board_position(), keep_actors_in_bounds(), and reset().
_bullets
std::vector<std::shared_ptr<Asteroids::Domain::Game::Actors::Bullet> > Asteroids::Domain::Game::Game::_bullets private
Definition at line 85 of file Game.h.
Referenced by get_actors(), and update().
_factory
std::unique_ptr<Asteroids::Domain::Factory::Factory> Asteroids::Domain::Game::Game::_factory private
Definition at line 61 of file Game.h.
Referenced by init().
_game_factory
std::unique_ptr<Asteroids::Domain::Game::GameFactoryInterface> Asteroids::Domain::Game::Game::_game_factory private
Definition at line 62 of file Game.h.
Referenced by init().
_is_active
bool Asteroids::Domain::Game::Game::_is_active private
Definition at line 69 of file Game.h.
Referenced by is_active(), maybe_lose_round(), maybe_win_round(), quit(), reset(), and start().
_is_round_active
bool Asteroids::Domain::Game::Game::_is_round_active private
Definition at line 70 of file Game.h.
Referenced by maybe_lose_round(), maybe_win_round(), reset(), and start_round().
_last_time_ms
long Asteroids::Domain::Game::Game::_last_time_ms private
Definition at line 72 of file Game.h.
Referenced by calculate_ticks_since_last_update(), and reset().
_player
std::shared_ptr<Actors::GunShip> Asteroids::Domain::Game::Game::_player private
Definition at line 81 of file Game.h.
Referenced by get_actors(), get_player(), init(), randomly_place_player(), and update().
_player_score
int Asteroids::Domain::Game::Game::_player_score private
Definition at line 82 of file Game.h.
Referenced by get_score(), reset(), and update().
_randomer
std::unique_ptr<Randomer> Asteroids::Domain::Game::Game::_randomer private
Definition at line 63 of file Game.h.
Referenced by get_random_board_position(), init(), and initialize_random_rocks().
_rocks
std::vector<std::shared_ptr<Asteroids::Domain::Game::Actors::Rock> > Asteroids::Domain::Game::Game::_rocks private
Definition at line 86 of file Game.h.
Referenced by get_actors(), initialize_random_rocks(), maybe_lose_round(), maybe_win_round(), and update().
_round_number
int Asteroids::Domain::Game::Game::_round_number private
Definition at line 71 of file Game.h.
Referenced by get_round(), reset(), start(), and start_round().
_ticks_per_second
long Asteroids::Domain::Game::Game::_ticks_per_second private
Definition at line 66 of file Game.h.
Referenced by get_ticks_per_second(), reset(), and wait_for_frames_per_second().
The documentation for this class was generated from the following files:
Domain/Game/Game.h
Domain/Game/Game.cpp