CPSC 462 - Asteroids: Asteroids::Domain::Game::Actors::Actor Class Reference
Asteroids::Domain::Game::Actors::Actor Class Reference
Implementation of ActorInterface.
#include <Actor.h>
Public Member Functions
Actor ()
double adjust_rotation (double radians)
bool check_collision (const Asteroids::Domain::Game::Actors::Actor &other_actor)
bool check_collision (std::shared_ptr< Asteroids::Domain::Game::Actors::Actor > other_actor)
void clear_input ()
std::vector< std::shared_ptr< Bullet > > get_fired_bullets (bool clear=true)
long get_lifetime_ticks ()
const std::vector< std::pair< double, double > > & get_polygon ()
std::pair< double, double > get_position ()
Rect get_rect () const
std::vector< std::pair< double, double > > get_rotated_polygon ()
double get_rotation ()
double get_x ()
double get_y ()
void reset ()
std::vector< std::pair< double, double > > rotate_polygon (double radians)
void set_input_down (bool b)
void set_input_fire (bool b)
void set_input_left (bool b)
void set_input_right (bool b)
void set_input_up (bool b)
void set_polygon (std::vector< std::pair< double, double >> points)
void set_position (double x, double y)
double set_rotation (double radians)
void set_velocity (double x, double y, double r)
void update (long elapsed_ticks)
bool wants_to_be_deleted ()
Protected Member Functions
void deleteme ()
void fire_bullet ()
void set_bullet_speed (double s)
void update_rect ()
Protected Attributes
bool _input_down
bool _input_fire
bool _input_left
bool _input_right
bool _input_up
std::unique_ptr< Vector > _vector
Private Member Functions
void apply_vector_to_position (long elapsed_ticks)
void init ()
Private Attributes
double _bullet_speed
std::vector< std::shared_ptr< Bullet > > _fired_bullets
long _lifetime_ticks
std::vector< std::pair< double, double > > _polygon_points
double _pos_x
double _pos_y
Rect _rect
double _rotation_radians
bool _wants_to_be_deleted
Detailed Description
Implementation of ActorInterface.
Definition at line 30 of file Actor.h.
Constructor & Destructor Documentation
Actor()
Asteroids::Domain::Game::Actors::Actor::Actor ()
Definition at line 32 of file Actor.cpp.
References init().
Member Function Documentation
adjust_rotation()
double Asteroids::Domain::Game::Actors::Actor::adjust_rotation (double radians)
Definition at line 258 of file Actor.cpp.
References _rotation_radians, and set_rotation().
apply_vector_to_position()
void Asteroids::Domain::Game::Actors::Actor::apply_vector_to_position (long elapsed_ticks) private
Definition at line 322 of file Actor.cpp.
References _pos_x, _pos_y, _rotation_radians, _vector, and update_rect().
Referenced by update().
check_collision() [1/2]
bool Asteroids::Domain::Game::Actors::Actor::check_collision (const Asteroids::Domain::Game::Actors::Actor & other_actor)
Definition at line 301 of file Actor.cpp.
References _rect, Asteroids::Domain::Game::Actors::Rect::collides_with_rect(), and get_rect().
Referenced by check_collision().
check_collision() [2/2]
bool Asteroids::Domain::Game::Actors::Actor::check_collision (std::shared_ptr< Asteroids::Domain::Game::Actors::Actor > other_actor)
Definition at line 315 of file Actor.cpp.
References check_collision().
clear_input()
void Asteroids::Domain::Game::Actors::Actor::clear_input () virtual
Implements Asteroids::Domain::Game::Actors::ActorInterface.
Definition at line 96 of file Actor.cpp.
References _input_down, _input_fire, _input_left, _input_right, and _input_up.
Referenced by reset().
deleteme()
void Asteroids::Domain::Game::Actors::Actor::deleteme () protected
Definition at line 347 of file Actor.cpp.
References _wants_to_be_deleted.
Referenced by Asteroids::Domain::Game::Actors::Bullet::maybe_die().
fire_bullet()
void Asteroids::Domain::Game::Actors::Actor::fire_bullet () protected
Definition at line 361 of file Actor.cpp.
References _bullet_speed, _fired_bullets, _vector, get_rotation(), get_x(), get_y(), and Asteroids::Domain::Game::Actors::Vector::rotate_velocity().
Referenced by Asteroids::Domain::Game::Actors::GunShip::use_input().
get_fired_bullets()
std::vector< std::shared_ptr< Bullet > > Asteroids::Domain::Game::Actors::Actor::get_fired_bullets (bool clear = true)
Definition at line 279 of file Actor.cpp.
References _fired_bullets.
get_lifetime_ticks()
long Asteroids::Domain::Game::Actors::Actor::get_lifetime_ticks ()
Definition at line 71 of file Actor.cpp.
References _lifetime_ticks.
Referenced by Asteroids::Domain::Game::Actors::Bullet::maybe_die().
get_polygon()
const std::vector< std::pair< double, double > > & Asteroids::Domain::Game::Actors::Actor::get_polygon () virtual
Implements Asteroids::Domain::Game::Actors::ActorInterface.
Definition at line 152 of file Actor.cpp.
References _polygon_points.
get_position()
std::pair< double, double > Asteroids::Domain::Game::Actors::Actor::get_position ()
Definition at line 225 of file Actor.cpp.
References _pos_x, and _pos_y.
get_rect()
Rect Asteroids::Domain::Game::Actors::Actor::get_rect () const
Definition at line 294 of file Actor.cpp.
References _rect.
Referenced by check_collision().
get_rotated_polygon()
std::vector< std::pair< double, double > > Asteroids::Domain::Game::Actors::Actor::get_rotated_polygon () virtual
Implements Asteroids::Domain::Game::Actors::ActorInterface.
Definition at line 159 of file Actor.cpp.
References _rotation_radians, and rotate_polygon().
get_rotation()
double Asteroids::Domain::Game::Actors::Actor::get_rotation ()
Definition at line 265 of file Actor.cpp.
References _rotation_radians.
Referenced by fire_bullet(), and Asteroids::Domain::Game::Actors::GunShip::use_input().
get_x()
double Asteroids::Domain::Game::Actors::Actor::get_x () virtual
Implements Asteroids::Domain::Game::Actors::ActorInterface.
Definition at line 237 of file Actor.cpp.
References _pos_x.
Referenced by fire_bullet().
get_y()
double Asteroids::Domain::Game::Actors::Actor::get_y () virtual
Implements Asteroids::Domain::Game::Actors::ActorInterface.
Definition at line 243 of file Actor.cpp.
References _pos_y.
Referenced by fire_bullet().
init()
void Asteroids::Domain::Game::Actors::Actor::init () private
Definition at line 39 of file Actor.cpp.
References _vector, and reset().
Referenced by Actor().
reset()
void Asteroids::Domain::Game::Actors::Actor::reset ()
Definition at line 51 of file Actor.cpp.
References _bullet_speed, _lifetime_ticks, _polygon_points, _pos_x, _pos_y, _rotation_radians, _wants_to_be_deleted, ASTEROIDS_GAME_BULLET_DEFAULT_SPEED, and clear_input().
Referenced by init(), Asteroids::Domain::Game::Actors::Bullet::reset(), Asteroids::Domain::Game::Actors::GunShip::reset(), and Asteroids::Domain::Game::Actors::Rock::reset().
rotate_polygon()
std::vector< std::pair< double, double > > Asteroids::Domain::Game::Actors::Actor::rotate_polygon (double radians)
Definition at line 166 of file Actor.cpp.
References _polygon_points.
Referenced by get_rotated_polygon().
set_bullet_speed()
void Asteroids::Domain::Game::Actors::Actor::set_bullet_speed (double s) protected
Definition at line 354 of file Actor.cpp.
References _bullet_speed.
Referenced by Asteroids::Domain::Game::Actors::GunShip::reset().
set_input_down()
void Asteroids::Domain::Game::Actors::Actor::set_input_down (bool b) virtual
Implements Asteroids::Domain::Game::Actors::ActorInterface.
Definition at line 114 of file Actor.cpp.
References _input_down.
set_input_fire()
void Asteroids::Domain::Game::Actors::Actor::set_input_fire (bool b) virtual
Implements Asteroids::Domain::Game::Actors::ActorInterface.
Definition at line 135 of file Actor.cpp.
References _input_fire.
Referenced by Asteroids::Domain::Game::Actors::GunShip::use_input().
set_input_left()
void Asteroids::Domain::Game::Actors::Actor::set_input_left (bool b) virtual
Implements Asteroids::Domain::Game::Actors::ActorInterface.
Definition at line 121 of file Actor.cpp.
References _input_left.
set_input_right()
void Asteroids::Domain::Game::Actors::Actor::set_input_right (bool b) virtual
Implements Asteroids::Domain::Game::Actors::ActorInterface.
Definition at line 128 of file Actor.cpp.
References _input_right.
set_input_up()
void Asteroids::Domain::Game::Actors::Actor::set_input_up (bool b) virtual
Implements Asteroids::Domain::Game::Actors::ActorInterface.
Definition at line 107 of file Actor.cpp.
References _input_up.
set_polygon()
void Asteroids::Domain::Game::Actors::Actor::set_polygon (std::vector< std::pair< double, double >> points)
Definition at line 142 of file Actor.cpp.
References _polygon_points, and update_rect().
Referenced by Asteroids::Domain::Game::Actors::LongRock::initialize_polygon(), Asteroids::Domain::Game::Actors::Rock::initialize_polygon(), Asteroids::Domain::Game::Actors::Bullet::initialize_polygon(), and Asteroids::Domain::Game::Actors::GunShip::initialize_polygon().
set_position()
void Asteroids::Domain::Game::Actors::Actor::set_position (double x, double y) virtual
Implements Asteroids::Domain::Game::Actors::ActorInterface.
Definition at line 214 of file Actor.cpp.
References _pos_x, _pos_y, and update_rect().
set_rotation()
double Asteroids::Domain::Game::Actors::Actor::set_rotation (double radians)
Definition at line 249 of file Actor.cpp.
References _rotation_radians.
Referenced by adjust_rotation().
set_velocity()
void Asteroids::Domain::Game::Actors::Actor::set_velocity (double x, double y, double r)
Definition at line 272 of file Actor.cpp.
References _vector.
update()
void Asteroids::Domain::Game::Actors::Actor::update (long elapsed_ticks)
Definition at line 85 of file Actor.cpp.
References _lifetime_ticks, _vector, and apply_vector_to_position().
Referenced by Asteroids::Domain::Game::Actors::Bullet::update(), and Asteroids::Domain::Game::Actors::GunShip::update().
update_rect()
void Asteroids::Domain::Game::Actors::Actor::update_rect () protected
Definition at line 339 of file Actor.cpp.
References _polygon_points, _pos_x, _pos_y, _rect, Asteroids::Domain::Game::Actors::Rect::add_offset(), and Asteroids::Domain::Game::Actors::Rect::consume_polygon().
Referenced by apply_vector_to_position(), set_polygon(), and set_position().
wants_to_be_deleted()
bool Asteroids::Domain::Game::Actors::Actor::wants_to_be_deleted ()
Definition at line 78 of file Actor.cpp.
References _wants_to_be_deleted.
Member Data Documentation
_bullet_speed
double Asteroids::Domain::Game::Actors::Actor::_bullet_speed private
Definition at line 134 of file Actor.h.
Referenced by fire_bullet(), reset(), and set_bullet_speed().
_fired_bullets
std::vector<std::shared_ptr<Bullet> > Asteroids::Domain::Game::Actors::Actor::_fired_bullets private
Definition at line 133 of file Actor.h.
Referenced by fire_bullet(), and get_fired_bullets().
_input_down
bool Asteroids::Domain::Game::Actors::Actor::_input_down protected
Definition at line 95 of file Actor.h.
Referenced by clear_input(), set_input_down(), and Asteroids::Domain::Game::Actors::GunShip::use_input().
_input_fire
bool Asteroids::Domain::Game::Actors::Actor::_input_fire protected
Definition at line 95 of file Actor.h.
Referenced by clear_input(), set_input_fire(), and Asteroids::Domain::Game::Actors::GunShip::use_input().
_input_left
bool Asteroids::Domain::Game::Actors::Actor::_input_left protected
Definition at line 95 of file Actor.h.
Referenced by clear_input(), set_input_left(), and Asteroids::Domain::Game::Actors::GunShip::use_input().
_input_right
bool Asteroids::Domain::Game::Actors::Actor::_input_right protected
Definition at line 95 of file Actor.h.
Referenced by clear_input(), set_input_right(), and Asteroids::Domain::Game::Actors::GunShip::use_input().
_input_up
bool Asteroids::Domain::Game::Actors::Actor::_input_up protected
Definition at line 95 of file Actor.h.
Referenced by clear_input(), set_input_up(), and Asteroids::Domain::Game::Actors::GunShip::use_input().
_lifetime_ticks
long Asteroids::Domain::Game::Actors::Actor::_lifetime_ticks private
Definition at line 116 of file Actor.h.
Referenced by get_lifetime_ticks(), reset(), and update().
_polygon_points
std::vector< std::pair<double, double> > Asteroids::Domain::Game::Actors::Actor::_polygon_points private
Definition at line 129 of file Actor.h.
Referenced by get_polygon(), reset(), rotate_polygon(), set_polygon(), and update_rect().
_pos_x
double Asteroids::Domain::Game::Actors::Actor::_pos_x private
Definition at line 121 of file Actor.h.
Referenced by apply_vector_to_position(), get_position(), get_x(), reset(), set_position(), and update_rect().
_pos_y
double Asteroids::Domain::Game::Actors::Actor::_pos_y private
Definition at line 121 of file Actor.h.
Referenced by apply_vector_to_position(), get_position(), get_y(), reset(), set_position(), and update_rect().
_rect
Rect Asteroids::Domain::Game::Actors::Actor::_rect private
Definition at line 130 of file Actor.h.
Referenced by check_collision(), get_rect(), and update_rect().
_rotation_radians
double Asteroids::Domain::Game::Actors::Actor::_rotation_radians private
Definition at line 121 of file Actor.h.
Referenced by adjust_rotation(), apply_vector_to_position(), get_rotated_polygon(), get_rotation(), reset(), and set_rotation().
_vector
std::unique_ptr<Vector> Asteroids::Domain::Game::Actors::Actor::_vector protected
Definition at line 91 of file Actor.h.
Referenced by apply_vector_to_position(), fire_bullet(), init(), set_velocity(), update(), and Asteroids::Domain::Game::Actors::GunShip::use_input().
_wants_to_be_deleted
bool Asteroids::Domain::Game::Actors::Actor::_wants_to_be_deleted private
Definition at line 117 of file Actor.h.
Referenced by deleteme(), reset(), and wants_to_be_deleted().
The documentation for this class was generated from the following files:
Domain/Game/Actors/Actor.h
Domain/Game/Actors/Actor.cpp