CPSC 462 - Asteroids: Asteroids::UI::ClientTextUI::DisplayGrid Class Reference
Asteroids::UI::ClientTextUI::DisplayGrid Class Reference
Class to help translate and render actors and stuff from the virtual game board, to actual ASCII graphics that can be seen.
#include <DisplayGrid.h>
Public Member Functions
DisplayGrid (double source_width, double source_height, int grid_width, int grid_height)
void clear ()
void draw_filled_polygon (double offset_x, double offset_y, const std::vector< std::pair< double, double >> &points)
void draw_polygon (double offset_x, double offset_y, const std::vector< std::pair< double, double >> &points)
void print ()
string render ()
void reset ()
void set_footer_text (string s)
void set_grid_pixel (int x, int y)
void set_header_text (string s)
void set_pixel (double x, double y)
Private Member Functions
void add_border ()
void calculate_translation ()
void clear_grid ()
void init ()
std::pair< int, int > translate_source_point (double x, double y)
Private Attributes
string _footer_text
string _header_text
int _height
double _source_height
double _source_width
double _translation_ratio
int _unused_height
double _unused_source_height
double _unused_source_width
int _unused_width
int _width
std::vector< std::vector< bool > > grid
Detailed Description
Class to help translate and render actors and stuff from the virtual game board, to actual ASCII graphics that can be seen.
Definition at line 28 of file DisplayGrid.h.
Constructor & Destructor Documentation
DisplayGrid()
Asteroids::UI::ClientTextUI::DisplayGrid::DisplayGrid (double source_width, double source_height, int grid_width, int grid_height)
Definition at line 29 of file DisplayGrid.cpp.
References _height, _source_height, _source_width, _width, and init().
Member Function Documentation
add_border()
void Asteroids::UI::ClientTextUI::DisplayGrid::add_border () private
Definition at line 102 of file DisplayGrid.cpp.
References _source_height, _source_width, and set_pixel().
Referenced by clear(), and clear_grid().
calculate_translation()
void Asteroids::UI::ClientTextUI::DisplayGrid::calculate_translation () private
Definition at line 54 of file DisplayGrid.cpp.
References _height, _source_height, _source_width, _translation_ratio, _unused_height, _unused_source_height, _unused_source_width, _unused_width, and _width.
Referenced by reset().
clear()
void Asteroids::UI::ClientTextUI::DisplayGrid::clear ()
Definition at line 135 of file DisplayGrid.cpp.
References add_border(), and grid.
clear_grid()
void Asteroids::UI::ClientTextUI::DisplayGrid::clear_grid () private
Definition at line 78 of file DisplayGrid.cpp.
References _height, _width, add_border(), and grid.
Referenced by reset().
draw_filled_polygon()
void Asteroids::UI::ClientTextUI::DisplayGrid::draw_filled_polygon (double offset_x, double offset_y, const std::vector< std::pair< double, double >> & points)
Definition at line 163 of file DisplayGrid.cpp.
References draw_polygon().
draw_polygon()
void Asteroids::UI::ClientTextUI::DisplayGrid::draw_polygon (double offset_x, double offset_y, const std::vector< std::pair< double, double >> & points)
Todo:
It'd be nice if we could finish connecting the polygon points with a line
Definition at line 219 of file DisplayGrid.cpp.
References set_pixel().
Referenced by draw_filled_polygon().
init()
void Asteroids::UI::ClientTextUI::DisplayGrid::init () private
Definition at line 47 of file DisplayGrid.cpp.
References reset().
Referenced by DisplayGrid().
print()
void Asteroids::UI::ClientTextUI::DisplayGrid::print ()
Definition at line 317 of file DisplayGrid.cpp.
References render().
render()
string Asteroids::UI::ClientTextUI::DisplayGrid::render ()
Definition at line 333 of file DisplayGrid.cpp.
References _footer_text, _header_text, _unused_width, and grid.
Referenced by print().
reset()
void Asteroids::UI::ClientTextUI::DisplayGrid::reset ()
Definition at line 121 of file DisplayGrid.cpp.
References _footer_text, _header_text, calculate_translation(), and clear_grid().
Referenced by init().
set_footer_text()
void Asteroids::UI::ClientTextUI::DisplayGrid::set_footer_text (string s)
Definition at line 156 of file DisplayGrid.cpp.
References _footer_text.
set_grid_pixel()
void Asteroids::UI::ClientTextUI::DisplayGrid::set_grid_pixel (int x, int y)
Definition at line 300 of file DisplayGrid.cpp.
References _height, _width, and grid.
Referenced by set_pixel().
set_header_text()
void Asteroids::UI::ClientTextUI::DisplayGrid::set_header_text (string s)
Definition at line 149 of file DisplayGrid.cpp.
References _header_text.
set_pixel()
void Asteroids::UI::ClientTextUI::DisplayGrid::set_pixel (double x, double y)
Definition at line 288 of file DisplayGrid.cpp.
References set_grid_pixel(), and translate_source_point().
Referenced by add_border(), and draw_polygon().
translate_source_point()
std::pair< int, int > Asteroids::UI::ClientTextUI::DisplayGrid::translate_source_point (double x, double y) private
Definition at line 380 of file DisplayGrid.cpp.
References _translation_ratio.
Referenced by set_pixel().
Member Data Documentation
_footer_text
string Asteroids::UI::ClientTextUI::DisplayGrid::_footer_text private
Definition at line 88 of file DisplayGrid.h.
Referenced by render(), reset(), and set_footer_text().
_header_text
string Asteroids::UI::ClientTextUI::DisplayGrid::_header_text private
Definition at line 88 of file DisplayGrid.h.
Referenced by render(), reset(), and set_header_text().
_height
int Asteroids::UI::ClientTextUI::DisplayGrid::_height private
Definition at line 72 of file DisplayGrid.h.
Referenced by calculate_translation(), clear_grid(), DisplayGrid(), and set_grid_pixel().
_source_height
double Asteroids::UI::ClientTextUI::DisplayGrid::_source_height private
Definition at line 78 of file DisplayGrid.h.
Referenced by add_border(), calculate_translation(), and DisplayGrid().
_source_width
double Asteroids::UI::ClientTextUI::DisplayGrid::_source_width private
Definition at line 78 of file DisplayGrid.h.
Referenced by add_border(), calculate_translation(), and DisplayGrid().
_translation_ratio
double Asteroids::UI::ClientTextUI::DisplayGrid::_translation_ratio private
Definition at line 83 of file DisplayGrid.h.
Referenced by calculate_translation(), and translate_source_point().
_unused_height
int Asteroids::UI::ClientTextUI::DisplayGrid::_unused_height private
Definition at line 72 of file DisplayGrid.h.
Referenced by calculate_translation().
_unused_source_height
double Asteroids::UI::ClientTextUI::DisplayGrid::_unused_source_height private
Definition at line 78 of file DisplayGrid.h.
Referenced by calculate_translation().
_unused_source_width
double Asteroids::UI::ClientTextUI::DisplayGrid::_unused_source_width private
Definition at line 78 of file DisplayGrid.h.
Referenced by calculate_translation().
_unused_width
int Asteroids::UI::ClientTextUI::DisplayGrid::_unused_width private
Definition at line 72 of file DisplayGrid.h.
Referenced by calculate_translation(), and render().
_width
int Asteroids::UI::ClientTextUI::DisplayGrid::_width private
Definition at line 72 of file DisplayGrid.h.
Referenced by calculate_translation(), clear_grid(), DisplayGrid(), and set_grid_pixel().
grid
std::vector<std::vector<bool> > Asteroids::UI::ClientTextUI::DisplayGrid::grid private
Definition at line 84 of file DisplayGrid.h.
Referenced by clear(), clear_grid(), render(), and set_grid_pixel().
The documentation for this class was generated from the following files:
UI/ClientTextUI/DisplayGrid.h
UI/ClientTextUI/DisplayGrid.cpp