CPSC 462 - Asteroids: Asteroids::Domain::Net::Messages::AUTH_STATE Class Reference
Asteroids::Domain::Net::Messages::AUTH_STATE Class Reference
Information about the current authentication state.
#include <AUTH_STATE.h>
Public Member Functions
AUTH_STATE ()
bool isAuthSuccessful ()
void reset ()
void setAuthSuccessful (bool b)
Private Attributes
bool _auth_successful
Detailed Description
Information about the current authentication state.
Currently only tells you whether or not you're authenticated
Definition at line 32 of file AUTH_STATE.h.
Constructor & Destructor Documentation
AUTH_STATE()
Asteroids::Domain::Net::Messages::AUTH_STATE::AUTH_STATE ()
Definition at line 20 of file AUTH_STATE.cpp.
References reset().
Member Function Documentation
isAuthSuccessful()
bool Asteroids::Domain::Net::Messages::AUTH_STATE::isAuthSuccessful ()
Definition at line 41 of file AUTH_STATE.cpp.
References _auth_successful.
reset()
void Asteroids::Domain::Net::Messages::AUTH_STATE::reset ()
Definition at line 27 of file AUTH_STATE.cpp.
References setAuthSuccessful().
Referenced by AUTH_STATE().
setAuthSuccessful()
void Asteroids::Domain::Net::Messages::AUTH_STATE::setAuthSuccessful (bool b)
Definition at line 34 of file AUTH_STATE.cpp.
References _auth_successful.
Referenced by reset().
Member Data Documentation
_auth_successful
bool Asteroids::Domain::Net::Messages::AUTH_STATE::_auth_successful private
Definition at line 51 of file AUTH_STATE.h.
Referenced by isAuthSuccessful(), and setAuthSuccessful().
The documentation for this class was generated from the following files:
Domain/Net/Messages/AUTH_STATE.h
Domain/Net/Messages/AUTH_STATE.cpp