CPSC 462 - Asteroids: Asteroids::Domain::Store::POWERUP_ADDED_INFO Class Reference
Asteroids::Domain::Store::POWERUP_ADDED_INFO Class Reference
Implementation of POWERUP_ADDED_INFO_INTERFACE.
#include <POWERUP_ADDED_INFO.h>
Public Member Functions
POWERUP_ADDED_INFO ()
size_t get_quantity ()
std::shared_ptr< Asteroids::Domain::Store::STORE_ITEM_INTERFACE > get_store_item ()
void reset ()
void set_quantity (size_t n)
void set_store_item (std::shared_ptr< Asteroids::Domain::Store::STORE_ITEM_INTERFACE > item)
Private Member Functions
void init ()
Private Attributes
std::shared_ptr< Asteroids::Domain::Store::STORE_ITEM_INTERFACE > _item
size_t _item_quantity
Detailed Description
Implementation of POWERUP_ADDED_INFO_INTERFACE.
Definition at line 20 of file POWERUP_ADDED_INFO.h.
Constructor & Destructor Documentation
POWERUP_ADDED_INFO()
Asteroids::Domain::Store::POWERUP_ADDED_INFO::POWERUP_ADDED_INFO ()
Definition at line 17 of file POWERUP_ADDED_INFO.cpp.
References init().
Member Function Documentation
get_quantity()
size_t Asteroids::Domain::Store::POWERUP_ADDED_INFO::get_quantity () virtual
Implements Asteroids::Domain::Store::POWERUP_ADDED_INFO_INTERFACE.
Definition at line 53 of file POWERUP_ADDED_INFO.cpp.
References _item_quantity.
get_store_item()
std::shared_ptr< Asteroids::Domain::Store::STORE_ITEM_INTERFACE > Asteroids::Domain::Store::POWERUP_ADDED_INFO::get_store_item () virtual
Implements Asteroids::Domain::Store::POWERUP_ADDED_INFO_INTERFACE.
Definition at line 39 of file POWERUP_ADDED_INFO.cpp.
References _item.
init()
void Asteroids::Domain::Store::POWERUP_ADDED_INFO::init () private
Definition at line 60 of file POWERUP_ADDED_INFO.cpp.
References reset().
Referenced by POWERUP_ADDED_INFO().
reset()
void Asteroids::Domain::Store::POWERUP_ADDED_INFO::reset ()
Definition at line 24 of file POWERUP_ADDED_INFO.cpp.
References _item, and _item_quantity.
Referenced by init().
set_quantity()
void Asteroids::Domain::Store::POWERUP_ADDED_INFO::set_quantity (size_t n) virtual
Implements Asteroids::Domain::Store::POWERUP_ADDED_INFO_INTERFACE.
Definition at line 46 of file POWERUP_ADDED_INFO.cpp.
References _item_quantity.
set_store_item()
void Asteroids::Domain::Store::POWERUP_ADDED_INFO::set_store_item (std::shared_ptr< Asteroids::Domain::Store::STORE_ITEM_INTERFACE > item) virtual
Implements Asteroids::Domain::Store::POWERUP_ADDED_INFO_INTERFACE.
Definition at line 32 of file POWERUP_ADDED_INFO.cpp.
References _item.
Member Data Documentation
_item
std::shared_ptr<Asteroids::Domain::Store::STORE_ITEM_INTERFACE> Asteroids::Domain::Store::POWERUP_ADDED_INFO::_item private
Definition at line 43 of file POWERUP_ADDED_INFO.h.
Referenced by get_store_item(), reset(), and set_store_item().
_item_quantity
size_t Asteroids::Domain::Store::POWERUP_ADDED_INFO::_item_quantity private
Definition at line 44 of file POWERUP_ADDED_INFO.h.
Referenced by get_quantity(), reset(), and set_quantity().
The documentation for this class was generated from the following files:
Domain/Store/POWERUP_ADDED_INFO.h
Domain/Store/POWERUP_ADDED_INFO.cpp