CPSC 462 - Asteroids: Asteroids::Domain::Net::Authentication::Authenticator Class Reference
Asteroids::Domain::Net::Authentication::Authenticator Class Reference
Implementation of AuthenticationInterface.
#include <Authenticator.h>
Public Member Functions
Authenticator ()
std::shared_ptr< Messages::AUTH_STATE > attemptLogin (string username, string password)
void reset ()
Private Member Functions
std::shared_ptr< Messages::AUTH_STATE > sendAuthToServer (std::shared_ptr< Messages::AUTH_ATTEMPT > auth)
Detailed Description
Implementation of AuthenticationInterface.
Definition at line 31 of file Authenticator.h.
Constructor & Destructor Documentation
Authenticator()
Asteroids::Domain::Net::Authentication::Authenticator::Authenticator ()
Definition at line 23 of file Authenticator.cpp.
References reset().
Member Function Documentation
attemptLogin()
std::shared_ptr< Messages::AUTH_STATE > Asteroids::Domain::Net::Authentication::Authenticator::attemptLogin (string username, string password) virtual
Implements Asteroids::Domain::Net::Authentication::AuthenticationInterface.
Definition at line 37 of file Authenticator.cpp.
References sendAuthToServer().
reset()
void Asteroids::Domain::Net::Authentication::Authenticator::reset ()
Definition at line 30 of file Authenticator.cpp.
Referenced by Authenticator().
sendAuthToServer()
std::shared_ptr< Messages::AUTH_STATE > Asteroids::Domain::Net::Authentication::Authenticator::sendAuthToServer (std::shared_ptr< Messages::AUTH_ATTEMPT > auth) private
Todo:
Stub function that always returns success!
Definition at line 61 of file Authenticator.cpp.
Referenced by attemptLogin().
The documentation for this class was generated from the following files:
Domain/Net/Authentication/Authenticator.h
Domain/Net/Authentication/Authenticator.cpp