CPSC 462 - Asteroids: Asteroids::Domain::Game::Randomer Class Reference
Asteroids::Domain::Game::Randomer Class Reference
Helper class to generate random numbers for the Game.
#include <Randomer.h>
Public Member Functions
Randomer ()
double get_double ()
double get_double (double min, double max)
void reset ()
bool roll_bool (double chance=0.5)
Private Member Functions
void init ()
Private Attributes
std::default_random_engine _random_engine
Detailed Description
Helper class to generate random numbers for the Game.
Definition at line 23 of file Randomer.h.
Constructor & Destructor Documentation
Randomer()
Asteroids::Domain::Game::Randomer::Randomer ()
Definition at line 21 of file Randomer.cpp.
References init().
Member Function Documentation
get_double() [1/2]
double Asteroids::Domain::Game::Randomer::get_double ()
Definition at line 48 of file Randomer.cpp.
Referenced by roll_bool().
get_double() [2/2]
double Asteroids::Domain::Game::Randomer::get_double (double min, double max)
Definition at line 55 of file Randomer.cpp.
References _random_engine.
init()
void Asteroids::Domain::Game::Randomer::init () private
Definition at line 28 of file Randomer.cpp.
References _random_engine, and reset().
Referenced by Randomer().
reset()
void Asteroids::Domain::Game::Randomer::reset ()
Definition at line 42 of file Randomer.cpp.
Referenced by init().
roll_bool()
bool Asteroids::Domain::Game::Randomer::roll_bool (double chance = 0.5)
Definition at line 66 of file Randomer.cpp.
References get_double().
Member Data Documentation
_random_engine
std::default_random_engine Asteroids::Domain::Game::Randomer::_random_engine private
Definition at line 45 of file Randomer.h.
Referenced by get_double(), and init().
The documentation for this class was generated from the following files:
Domain/Game/Randomer.h
Domain/Game/Randomer.cpp