CPSC 462 - Asteroids: Asteroids::Domain::Game::GAME_HISTORY_ENTRY Class Reference
Asteroids::Domain::Game::GAME_HISTORY_ENTRY Class Reference
Implements GAME_HISTORY_ENTRY_INTERFACE.
#include <GAME_HISTORY_ENTRY.h>
Public Member Functions
GAME_HISTORY_ENTRY ()
std::string get_date ()
std::string get_id ()
int get_score ()
void reset ()
void set_date (std::string d)
void set_id (std::string id)
void set_score (int s)
Private Attributes
std::string _date
std::string _id
int _score
Detailed Description
Implements GAME_HISTORY_ENTRY_INTERFACE.
Definition at line 25 of file GAME_HISTORY_ENTRY.h.
Constructor & Destructor Documentation
GAME_HISTORY_ENTRY()
Asteroids::Domain::Game::GAME_HISTORY_ENTRY::GAME_HISTORY_ENTRY ()
Definition at line 21 of file GAME_HISTORY_ENTRY.cpp.
References reset().
Member Function Documentation
get_date()
string Asteroids::Domain::Game::GAME_HISTORY_ENTRY::get_date () virtual
Implements Asteroids::Domain::Game::GAME_HISTORY_ENTRY_INTERFACE.
Definition at line 57 of file GAME_HISTORY_ENTRY.cpp.
References _date.
get_id()
std::string Asteroids::Domain::Game::GAME_HISTORY_ENTRY::get_id () virtual
Implements Asteroids::Domain::Game::GAME_HISTORY_ENTRY_INTERFACE.
Definition at line 43 of file GAME_HISTORY_ENTRY.cpp.
References _id.
get_score()
int Asteroids::Domain::Game::GAME_HISTORY_ENTRY::get_score () virtual
Implements Asteroids::Domain::Game::GAME_HISTORY_ENTRY_INTERFACE.
Definition at line 71 of file GAME_HISTORY_ENTRY.cpp.
References _score.
reset()
void Asteroids::Domain::Game::GAME_HISTORY_ENTRY::reset ()
Definition at line 28 of file GAME_HISTORY_ENTRY.cpp.
References set_date(), and set_score().
Referenced by GAME_HISTORY_ENTRY().
set_date()
void Asteroids::Domain::Game::GAME_HISTORY_ENTRY::set_date (std::string d) virtual
Implements Asteroids::Domain::Game::GAME_HISTORY_ENTRY_INTERFACE.
Definition at line 50 of file GAME_HISTORY_ENTRY.cpp.
References _date.
Referenced by reset().
set_id()
void Asteroids::Domain::Game::GAME_HISTORY_ENTRY::set_id (std::string id) virtual
Implements Asteroids::Domain::Game::GAME_HISTORY_ENTRY_INTERFACE.
Definition at line 36 of file GAME_HISTORY_ENTRY.cpp.
References _id.
set_score()
void Asteroids::Domain::Game::GAME_HISTORY_ENTRY::set_score (int s) virtual
Implements Asteroids::Domain::Game::GAME_HISTORY_ENTRY_INTERFACE.
Definition at line 64 of file GAME_HISTORY_ENTRY.cpp.
References _score.
Referenced by reset().
Member Data Documentation
_date
std::string Asteroids::Domain::Game::GAME_HISTORY_ENTRY::_date private
Definition at line 54 of file GAME_HISTORY_ENTRY.h.
Referenced by get_date(), and set_date().
_id
std::string Asteroids::Domain::Game::GAME_HISTORY_ENTRY::_id private
Definition at line 53 of file GAME_HISTORY_ENTRY.h.
Referenced by get_id(), and set_id().
_score
int Asteroids::Domain::Game::GAME_HISTORY_ENTRY::_score private
Definition at line 55 of file GAME_HISTORY_ENTRY.h.
Referenced by get_score(), and set_score().
The documentation for this class was generated from the following files:
Domain/Game/GAME_HISTORY_ENTRY.h
Domain/Game/GAME_HISTORY_ENTRY.cpp