CPSC 462 - Asteroids: Asteroids::Domain::Factory::Factory Class Reference
Asteroids::Domain::Factory::Factory Class Reference
Implementation of FactoryInterface.
#include <Factory.h>
Public Member Functions
Factory ()
std::unique_ptr< Asteroids::Domain::Game::GameFactoryInterface > createGameFactory ()
std::unique_ptr< Asteroids::Domain::Net::NetFactoryInterface > createNetworkFactory ()
std::unique_ptr< Asteroids::Domain::Server::ServerFactoryInterface > createServerFactory ()
std::unique_ptr< Asteroids::Domain::Store::StoreFactoryInterface > createStoreFactory ()
std::unique_ptr< Asteroids::TechnicalServices::TechnicalServicesFactoryInterface > createTechnicalServicesFactory ()
std::unique_ptr< Asteroids::UI::UIFactoryInterface > createUIFactory ()
void reset ()
Private Member Functions
std::shared_ptr< Factory > this_pointer ()
Detailed Description
Implementation of FactoryInterface.
Definition at line 23 of file Factory.h.
Constructor & Destructor Documentation
Factory()
Asteroids::Domain::Factory::Factory::Factory ()
Definition at line 24 of file Factory.cpp.
References reset().
Member Function Documentation
createGameFactory()
std::unique_ptr< Asteroids::Domain::Game::GameFactoryInterface > Asteroids::Domain::Factory::Factory::createGameFactory () virtual
Implements Asteroids::Domain::Factory::FactoryInterface.
Definition at line 48 of file Factory.cpp.
createNetworkFactory()
std::unique_ptr< Asteroids::Domain::Net::NetFactoryInterface > Asteroids::Domain::Factory::Factory::createNetworkFactory () virtual
Implements Asteroids::Domain::Factory::FactoryInterface.
Definition at line 59 of file Factory.cpp.
createServerFactory()
std::unique_ptr< Asteroids::Domain::Server::ServerFactoryInterface > Asteroids::Domain::Factory::Factory::createServerFactory () virtual
Implements Asteroids::Domain::Factory::FactoryInterface.
Definition at line 37 of file Factory.cpp.
References this_pointer().
createStoreFactory()
std::unique_ptr< Asteroids::Domain::Store::StoreFactoryInterface > Asteroids::Domain::Factory::Factory::createStoreFactory () virtual
Implements Asteroids::Domain::Factory::FactoryInterface.
Definition at line 70 of file Factory.cpp.
References this_pointer().
createTechnicalServicesFactory()
std::unique_ptr< Asteroids::TechnicalServices::TechnicalServicesFactoryInterface > Asteroids::Domain::Factory::Factory::createTechnicalServicesFactory () virtual
Implements Asteroids::Domain::Factory::FactoryInterface.
Definition at line 92 of file Factory.cpp.
createUIFactory()
std::unique_ptr< Asteroids::UI::UIFactoryInterface > Asteroids::Domain::Factory::Factory::createUIFactory () virtual
Implements Asteroids::Domain::Factory::FactoryInterface.
Definition at line 81 of file Factory.cpp.
References this_pointer().
reset()
void Asteroids::Domain::Factory::Factory::reset ()
Definition at line 31 of file Factory.cpp.
Referenced by Factory().
this_pointer()
std::shared_ptr< Factory > Asteroids::Domain::Factory::Factory::this_pointer () private
Definition at line 103 of file Factory.cpp.
Referenced by createServerFactory(), createStoreFactory(), and createUIFactory().
The documentation for this class was generated from the following files:
Domain/Factory/Factory.h
Domain/Factory/Factory.cpp