CPSC 462 - Asteroids: Asteroids::Domain::Game::Actors::Vector Class Reference
Asteroids::Domain::Game::Actors::Vector Class Reference
Simple class to store 2D vector and rotation, to lend physics to game actors.
#include <Vector.h>
Public Member Functions
Vector ()
std::pair< double, double > adjust (double x, double y, double r=0.0)
std::pair< double, double > get_linear ()
std::pair< double, double > get_rotated_linear ()
double get_rotational ()
double get_x ()
double get_y ()
void reset ()
std::pair< double, double > set (double x, double y, double r)
void update (long ticks)
Static Public Member Functions
static std::pair< double, double > rotate_velocity (double x, double y, double rotate_radians)
Private Member Functions
void apply_limits ()
void dampen (long ticks)
Private Attributes
double _r
double _x
double _y
Detailed Description
Simple class to store 2D vector and rotation, to lend physics to game actors.
Definition at line 26 of file Vector.h.
Constructor & Destructor Documentation
Vector()
Asteroids::Domain::Game::Actors::Vector::Vector ()
Definition at line 26 of file Vector.cpp.
References reset().
Member Function Documentation
adjust()
std::pair< double, double > Asteroids::Domain::Game::Actors::Vector::adjust (double x, double y, double r = 0.0)
Definition at line 41 of file Vector.cpp.
References _r, _x, and _y.
apply_limits()
void Asteroids::Domain::Game::Actors::Vector::apply_limits () private
Definition at line 127 of file Vector.cpp.
References _r, _x, _y, ASTEROIDS_GAME_VELOCITY_MAX, and ASTEROIDS_GAME_VELOCITY_ROTATIONAL_MAX.
Referenced by update().
dampen()
void Asteroids::Domain::Game::Actors::Vector::dampen (long ticks) private
Definition at line 155 of file Vector.cpp.
References _r, _x, _y, and ASTEROIDS_GAME_VELOCITY_DAMPENING_TICKS_FACTOR.
Referenced by update().
get_linear()
std::pair< double, double > Asteroids::Domain::Game::Actors::Vector::get_linear ()
Definition at line 59 of file Vector.cpp.
References _x, and _y.
Referenced by set().
get_rotated_linear()
std::pair< double, double > Asteroids::Domain::Game::Actors::Vector::get_rotated_linear ()
Definition at line 66 of file Vector.cpp.
References _r, _x, _y, and rotate_velocity().
get_rotational()
double Asteroids::Domain::Game::Actors::Vector::get_rotational ()
Definition at line 91 of file Vector.cpp.
References _r.
get_x()
double Asteroids::Domain::Game::Actors::Vector::get_x ()
Definition at line 77 of file Vector.cpp.
References _x.
get_y()
double Asteroids::Domain::Game::Actors::Vector::get_y ()
Definition at line 84 of file Vector.cpp.
References _y.
reset()
void Asteroids::Domain::Game::Actors::Vector::reset ()
Definition at line 33 of file Vector.cpp.
References _x, and _y.
Referenced by Vector().
rotate_velocity()
std::pair< double, double > Asteroids::Domain::Game::Actors::Vector::rotate_velocity (double x, double y, double rotate_radians) static
Definition at line 98 of file Vector.cpp.
Referenced by Asteroids::Domain::Game::Actors::Actor::fire_bullet(), get_rotated_linear(), and Asteroids::Domain::Game::Actors::GunShip::use_input().
set()
std::pair< double, double > Asteroids::Domain::Game::Actors::Vector::set (double x, double y, double r)
Definition at line 48 of file Vector.cpp.
References _r, _x, _y, and get_linear().
update()
void Asteroids::Domain::Game::Actors::Vector::update (long ticks)
Definition at line 119 of file Vector.cpp.
References apply_limits(), and dampen().
Member Data Documentation
_r
double Asteroids::Domain::Game::Actors::Vector::_r private
Definition at line 56 of file Vector.h.
Referenced by adjust(), apply_limits(), dampen(), get_rotated_linear(), get_rotational(), and set().
_x
double Asteroids::Domain::Game::Actors::Vector::_x private
Definition at line 56 of file Vector.h.
Referenced by adjust(), apply_limits(), dampen(), get_linear(), get_rotated_linear(), get_x(), reset(), and set().
_y
double Asteroids::Domain::Game::Actors::Vector::_y private
Definition at line 56 of file Vector.h.
Referenced by adjust(), apply_limits(), dampen(), get_linear(), get_rotated_linear(), get_y(), reset(), and set().
The documentation for this class was generated from the following files:
Domain/Game/Actors/Vector.h
Domain/Game/Actors/Vector.cpp