CPSC 462 - Asteroids: Asteroids::UI::ClientTextUI::ClientTextUI Class Reference
Asteroids::UI::ClientTextUI::ClientTextUI Class Reference
Implementation of ClientTextUIInterface.
#include <ClientTextUI.h>
Public Member Functions
ClientTextUI (std::shared_ptr< Asteroids::Domain::Factory::FactoryInterface > factory)
void reset ()
void run ()
Begin the user interface.
Private Member Functions
bool demand_authentication ()
void do_authentication ()
void draw_actor (std::shared_ptr< Asteroids::Domain::Game::Actors::ActorInterface > actor)
void draw_game ()
void find_friends_on_social_media ()
void handle_game_input ()
void init ()
void initialize_display_grid ()
Enums::MainMenuChoice main_menu ()
void main_menu_loop ()
bool pay_for_store_item (std::shared_ptr< Asteroids::Domain::Store::STORE_ITEM_INTERFACE > item, Asteroids::Domain::Store::Enums::PaymentMethod payment_method)
std::shared_ptr< Asteroids::Domain::Store::PAYMENT_RESULT_DETAILS_INTERFACE > pay_for_store_item_with_credit_card (std::shared_ptr< Asteroids::Domain::Store::STORE_ITEM_INTERFACE > item)
void play_game ()
void print (string s="", bool do_newline=true)
std::shared_ptr< Asteroids::Domain::Store::POWERUP_ADDED_INFO_INTERFACE > purchasing_store_item (std::shared_ptr< Asteroids::Domain::Store::STORE_ITEM_INTERFACE > item)
void review_game_history ()
void share_game_history_entry_to_social_media (std::shared_ptr< Asteroids::Domain::Game::GAME_HISTORY_ENTRY_INTERFACE > entry)
void store ()
bool store_loop ()
void store_offer_available_items ()
Private Attributes
std::shared_ptr< Asteroids::Domain::Net::Messages::AUTH_STATE > _authentication_state
std::unique_ptr< Asteroids::UI::ClientTextUI::DisplayGrid > _display_grid
std::shared_ptr< Asteroids::Domain::Factory::FactoryInterface > _factory
std::shared_ptr< Asteroids::Domain::Game::GameInterface > _game
std::unique_ptr< Asteroids::Domain::Game::GameFactoryInterface > _game_factory
std::shared_ptr< Asteroids::Domain::Game::GameHistoryInterface > _game_history
std::unique_ptr< Asteroids::UI::ClientTextUI::Input > _input
std::unique_ptr< Asteroids::Domain::Net::NetFactoryInterface > _net_factory
std::shared_ptr< Asteroids::Domain::Store::PaymentHelperInterface > _payment_helper
std::shared_ptr< Asteroids::Domain::Store::StoreInterface > _store
std::unique_ptr< Asteroids::Domain::Store::StoreFactoryInterface > _store_factory
std::unique_ptr< Asteroids::TechnicalServices::TechnicalServicesFactoryInterface > _technical_services_factory
Detailed Description
Implementation of ClientTextUIInterface.
Definition at line 54 of file ClientTextUI.h.
Constructor & Destructor Documentation
ClientTextUI()
Asteroids::UI::ClientTextUI::ClientTextUI::ClientTextUI (std::shared_ptr< Asteroids::Domain::Factory::FactoryInterface > factory)
Definition at line 57 of file ClientTextUI.cpp.
References _factory, init(), and reset().
Member Function Documentation
demand_authentication()
bool Asteroids::UI::ClientTextUI::ClientTextUI::demand_authentication () private
Definition at line 143 of file ClientTextUI.cpp.
References _authentication_state, do_authentication(), and print().
Referenced by run().
do_authentication()
void Asteroids::UI::ClientTextUI::ClientTextUI::do_authentication () private
Definition at line 164 of file ClientTextUI.cpp.
References _authentication_state, _net_factory, Asteroids::Domain::Net::Authentication::AuthenticationInterface::attemptLogin(), and print().
Referenced by demand_authentication().
draw_actor()
void Asteroids::UI::ClientTextUI::ClientTextUI::draw_actor (std::shared_ptr< Asteroids::Domain::Game::Actors::ActorInterface > actor) private
Definition at line 375 of file ClientTextUI.cpp.
References _display_grid.
Referenced by draw_game().
draw_game()
void Asteroids::UI::ClientTextUI::ClientTextUI::draw_game () private
Definition at line 348 of file ClientTextUI.cpp.
References _display_grid, _game, and draw_actor().
Referenced by play_game().
find_friends_on_social_media()
void Asteroids::UI::ClientTextUI::ClientTextUI::find_friends_on_social_media () private
Todo:
Actually navigate to the friend's social media account, somehow
Definition at line 468 of file ClientTextUI.cpp.
References _technical_services_factory, and print().
Referenced by main_menu_loop().
handle_game_input()
void Asteroids::UI::ClientTextUI::ClientTextUI::handle_game_input () private
Definition at line 308 of file ClientTextUI.cpp.
References _game, _input, Asteroids::UI::ClientTextUI::Input::KEY_DOWN, Asteroids::UI::ClientTextUI::Input::KEY_FIRE, Asteroids::UI::ClientTextUI::Input::KEY_LEFT, Asteroids::UI::ClientTextUI::Input::KEY_RIGHT, Asteroids::UI::ClientTextUI::Input::KEY_UP, and print().
Referenced by play_game().
init()
void Asteroids::UI::ClientTextUI::ClientTextUI::init () private
Todo:
Make a TextUI Factory instead of doing this here
Definition at line 68 of file ClientTextUI.cpp.
References _factory, _game_factory, _input, _net_factory, _store_factory, and _technical_services_factory.
Referenced by ClientTextUI().
initialize_display_grid()
void Asteroids::UI::ClientTextUI::ClientTextUI::initialize_display_grid () private
Todo:
Make a TextUI Factory instead of doing this here
Definition at line 83 of file ClientTextUI.cpp.
References _display_grid, _game, ASTEROIDS_UI_TEXTUI_DISPLAYGRID_HEIGHT, and ASTEROIDS_UI_TEXTUI_DISPLAYGRID_WIDTH.
Referenced by play_game().
main_menu()
Enums::MainMenuChoice Asteroids::UI::ClientTextUI::ClientTextUI::main_menu () private
Definition at line 233 of file ClientTextUI.cpp.
References Asteroids::UI::ClientTextUI::Enums::FindFriendsOnSocialMedia, Asteroids::UI::ClientTextUI::Enums::Invalid, Asteroids::UI::ClientTextUI::Enums::PlayGame, Asteroids::UI::ClientTextUI::Enums::PowerUpStore, print(), Asteroids::UI::ClientTextUI::Enums::Quit, and Asteroids::UI::ClientTextUI::Enums::ReviewGameHistory.
Referenced by main_menu_loop().
main_menu_loop()
void Asteroids::UI::ClientTextUI::ClientTextUI::main_menu_loop () private
Definition at line 185 of file ClientTextUI.cpp.
References find_friends_on_social_media(), Asteroids::UI::ClientTextUI::Enums::FindFriendsOnSocialMedia, Asteroids::UI::ClientTextUI::Enums::Invalid, main_menu(), play_game(), Asteroids::UI::ClientTextUI::Enums::PlayGame, Asteroids::UI::ClientTextUI::Enums::PowerUpStore, print(), Asteroids::UI::ClientTextUI::Enums::Quit, review_game_history(), Asteroids::UI::ClientTextUI::Enums::ReviewGameHistory, and store().
Referenced by run().
pay_for_store_item()
bool Asteroids::UI::ClientTextUI::ClientTextUI::pay_for_store_item (std::shared_ptr< Asteroids::Domain::Store::STORE_ITEM_INTERFACE > item, Asteroids::Domain::Store::Enums::PaymentMethod payment_method) private
Definition at line 750 of file ClientTextUI.cpp.
References _payment_helper, Asteroids::Domain::Store::Enums::CreditCard, pay_for_store_item_with_credit_card(), and print().
Referenced by purchasing_store_item().
pay_for_store_item_with_credit_card()
std::shared_ptr< Asteroids::Domain::Store::PAYMENT_RESULT_DETAILS_INTERFACE > Asteroids::UI::ClientTextUI::ClientTextUI::pay_for_store_item_with_credit_card (std::shared_ptr< Asteroids::Domain::Store::STORE_ITEM_INTERFACE > item) private
Definition at line 804 of file ClientTextUI.cpp.
References _payment_helper, and print().
Referenced by pay_for_store_item().
play_game()
void Asteroids::UI::ClientTextUI::ClientTextUI::play_game () private
Definition at line 277 of file ClientTextUI.cpp.
References _game, _game_factory, _input, draw_game(), handle_game_input(), initialize_display_grid(), and print().
Referenced by main_menu_loop().
print()
void Asteroids::UI::ClientTextUI::ClientTextUI::print (string s = "", bool do_newline = true) private
Definition at line 102 of file ClientTextUI.cpp.
Referenced by demand_authentication(), do_authentication(), find_friends_on_social_media(), handle_game_input(), main_menu(), main_menu_loop(), pay_for_store_item(), pay_for_store_item_with_credit_card(), play_game(), purchasing_store_item(), review_game_history(), run(), share_game_history_entry_to_social_media(), store(), store_loop(), and store_offer_available_items().
purchasing_store_item()
std::shared_ptr< Asteroids::Domain::Store::POWERUP_ADDED_INFO_INTERFACE > Asteroids::UI::ClientTextUI::ClientTextUI::purchasing_store_item (std::shared_ptr< Asteroids::Domain::Store::STORE_ITEM_INTERFACE > item) private
Definition at line 679 of file ClientTextUI.cpp.
References _payment_helper, _store_factory, pay_for_store_item(), and print().
Referenced by store_offer_available_items().
reset()
void Asteroids::UI::ClientTextUI::ClientTextUI::reset ()
Definition at line 120 of file ClientTextUI.cpp.
References _authentication_state.
Referenced by ClientTextUI().
review_game_history()
void Asteroids::UI::ClientTextUI::ClientTextUI::review_game_history () private
Definition at line 385 of file ClientTextUI.cpp.
References _game_factory, _game_history, print(), and share_game_history_entry_to_social_media().
Referenced by main_menu_loop().
run()
void Asteroids::UI::ClientTextUI::ClientTextUI::run () virtual
Begin the user interface.
Implements Asteroids::UI::ClientTextUI::ClientTextUIInterface.
Definition at line 127 of file ClientTextUI.cpp.
References demand_authentication(), main_menu_loop(), and print().
share_game_history_entry_to_social_media()
void Asteroids::UI::ClientTextUI::ClientTextUI::share_game_history_entry_to_social_media (std::shared_ptr< Asteroids::Domain::Game::GAME_HISTORY_ENTRY_INTERFACE > entry) private
Definition at line 436 of file ClientTextUI.cpp.
References _net_factory, _technical_services_factory, Asteroids::Domain::Net::ClientServerCommunicatorInterface::notifyServerOfGameHistoryEntrySocialMediaShare(), and print().
Referenced by review_game_history().
store()
void Asteroids::UI::ClientTextUI::ClientTextUI::store () private
Definition at line 534 of file ClientTextUI.cpp.
References _payment_helper, _store, _store_factory, print(), and store_loop().
Referenced by main_menu_loop().
store_loop()
bool Asteroids::UI::ClientTextUI::ClientTextUI::store_loop () private
Definition at line 553 of file ClientTextUI.cpp.
References print(), and store_offer_available_items().
Referenced by store().
store_offer_available_items()
void Asteroids::UI::ClientTextUI::ClientTextUI::store_offer_available_items () private
Definition at line 591 of file ClientTextUI.cpp.
References _store, print(), and purchasing_store_item().
Referenced by store_loop().
Member Data Documentation
_authentication_state
std::shared_ptr<Asteroids::Domain::Net::Messages::AUTH_STATE> Asteroids::UI::ClientTextUI::ClientTextUI::_authentication_state private
Definition at line 80 of file ClientTextUI.h.
Referenced by demand_authentication(), do_authentication(), and reset().
_display_grid
std::unique_ptr<Asteroids::UI::ClientTextUI::DisplayGrid> Asteroids::UI::ClientTextUI::ClientTextUI::_display_grid private
Definition at line 85 of file ClientTextUI.h.
Referenced by draw_actor(), draw_game(), and initialize_display_grid().
_factory
std::shared_ptr<Asteroids::Domain::Factory::FactoryInterface> Asteroids::UI::ClientTextUI::ClientTextUI::_factory private
Definition at line 73 of file ClientTextUI.h.
Referenced by ClientTextUI(), and init().
_game
std::shared_ptr<Asteroids::Domain::Game::GameInterface> Asteroids::UI::ClientTextUI::ClientTextUI::_game private
Definition at line 83 of file ClientTextUI.h.
Referenced by draw_game(), handle_game_input(), initialize_display_grid(), and play_game().
_game_factory
std::unique_ptr<Asteroids::Domain::Game::GameFactoryInterface> Asteroids::UI::ClientTextUI::ClientTextUI::_game_factory private
Definition at line 74 of file ClientTextUI.h.
Referenced by init(), play_game(), and review_game_history().
_game_history
std::shared_ptr<Asteroids::Domain::Game::GameHistoryInterface> Asteroids::UI::ClientTextUI::ClientTextUI::_game_history private
Definition at line 88 of file ClientTextUI.h.
Referenced by review_game_history().
_input
std::unique_ptr<Asteroids::UI::ClientTextUI::Input> Asteroids::UI::ClientTextUI::ClientTextUI::_input private
Definition at line 84 of file ClientTextUI.h.
Referenced by handle_game_input(), init(), and play_game().
_net_factory
std::unique_ptr<Asteroids::Domain::Net::NetFactoryInterface> Asteroids::UI::ClientTextUI::ClientTextUI::_net_factory private
Definition at line 75 of file ClientTextUI.h.
Referenced by do_authentication(), init(), and share_game_history_entry_to_social_media().
_payment_helper
std::shared_ptr<Asteroids::Domain::Store::PaymentHelperInterface> Asteroids::UI::ClientTextUI::ClientTextUI::_payment_helper private
Definition at line 92 of file ClientTextUI.h.
Referenced by pay_for_store_item(), pay_for_store_item_with_credit_card(), purchasing_store_item(), and store().
_store
std::shared_ptr<Asteroids::Domain::Store::StoreInterface> Asteroids::UI::ClientTextUI::ClientTextUI::_store private
Definition at line 91 of file ClientTextUI.h.
Referenced by store(), and store_offer_available_items().
_store_factory
std::unique_ptr<Asteroids::Domain::Store::StoreFactoryInterface> Asteroids::UI::ClientTextUI::ClientTextUI::_store_factory private
Definition at line 76 of file ClientTextUI.h.
Referenced by init(), purchasing_store_item(), and store().
_technical_services_factory
std::unique_ptr<Asteroids::TechnicalServices::TechnicalServicesFactoryInterface> Asteroids::UI::ClientTextUI::ClientTextUI::_technical_services_factory private
Definition at line 77 of file ClientTextUI.h.
Referenced by find_friends_on_social_media(), init(), and share_game_history_entry_to_social_media().
The documentation for this class was generated from the following files:
UI/ClientTextUI/ClientTextUI.h
UI/ClientTextUI/ClientTextUI.cpp