CPSC 462 - Asteroids: Asteroids::Domain::Game::Actors::Bullet Class Reference
Asteroids::Domain::Game::Actors::Bullet Class Reference
A bullet is... a bullet... Can be shot by the player (eventually Alien too); Player's bullet kills rocks/alien; Alien bullet kills rocks/player.
#include <Bullet.h>
Public Member Functions
Bullet ()
void reset ()
void update (long ticks)
Public Member Functions inherited from Asteroids::Domain::Game::Actors::Actor
Actor ()
double adjust_rotation (double radians)
bool check_collision (const Asteroids::Domain::Game::Actors::Actor &other_actor)
bool check_collision (std::shared_ptr< Asteroids::Domain::Game::Actors::Actor > other_actor)
void clear_input ()
std::vector< std::shared_ptr< Bullet > > get_fired_bullets (bool clear=true)
long get_lifetime_ticks ()
const std::vector< std::pair< double, double > > & get_polygon ()
std::pair< double, double > get_position ()
Rect get_rect () const
std::vector< std::pair< double, double > > get_rotated_polygon ()
double get_rotation ()
double get_x ()
double get_y ()
void reset ()
std::vector< std::pair< double, double > > rotate_polygon (double radians)
void set_input_down (bool b)
void set_input_fire (bool b)
void set_input_left (bool b)
void set_input_right (bool b)
void set_input_up (bool b)
void set_polygon (std::vector< std::pair< double, double >> points)
void set_position (double x, double y)
double set_rotation (double radians)
void set_velocity (double x, double y, double r)
void update (long elapsed_ticks)
bool wants_to_be_deleted ()
Private Member Functions
void init ()
void initialize_polygon ()
void maybe_die ()
Additional Inherited Members
Protected Member Functions inherited from Asteroids::Domain::Game::Actors::Actor
void deleteme ()
void fire_bullet ()
void set_bullet_speed (double s)
void update_rect ()
Protected Attributes inherited from Asteroids::Domain::Game::Actors::Actor
bool _input_down
bool _input_fire
bool _input_left
bool _input_right
bool _input_up
std::unique_ptr< Vector > _vector
Detailed Description
A bullet is... a bullet... Can be shot by the player (eventually Alien too); Player's bullet kills rocks/alien; Alien bullet kills rocks/player.
Definition at line 23 of file Bullet.h.
Constructor & Destructor Documentation
Bullet()
Asteroids::Domain::Game::Actors::Bullet::Bullet ()
Definition at line 20 of file Bullet.cpp.
References init().
Member Function Documentation
init()
void Asteroids::Domain::Game::Actors::Bullet::init () private
Definition at line 27 of file Bullet.cpp.
References reset().
Referenced by Bullet().
initialize_polygon()
void Asteroids::Domain::Game::Actors::Bullet::initialize_polygon () private
Definition at line 63 of file Bullet.cpp.
References Asteroids::Domain::Game::Actors::Actor::set_polygon().
Referenced by reset().
maybe_die()
void Asteroids::Domain::Game::Actors::Bullet::maybe_die () private
Definition at line 54 of file Bullet.cpp.
References ASTEROIDS_GAME_BULLET_LIFETIME_TICKS, Asteroids::Domain::Game::Actors::Actor::deleteme(), and Asteroids::Domain::Game::Actors::Actor::get_lifetime_ticks().
Referenced by update().
reset()
void Asteroids::Domain::Game::Actors::Bullet::reset ()
Definition at line 34 of file Bullet.cpp.
References initialize_polygon(), and Asteroids::Domain::Game::Actors::Actor::reset().
Referenced by init().
update()
void Asteroids::Domain::Game::Actors::Bullet::update (long ticks)
Definition at line 44 of file Bullet.cpp.
References maybe_die(), and Asteroids::Domain::Game::Actors::Actor::update().
The documentation for this class was generated from the following files:
Domain/Game/Actors/Bullet.h
Domain/Game/Actors/Bullet.cpp