.TH "TechnicalServices/Social Directory Reference" 3 "Fri Dec 14 2018" "CPSC 462 - Asteroids" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TechnicalServices/Social Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBFRIEND_ON_SOCIAL_MEDIA\&.cpp\fP"
.br
.ti -1c
.RI "file \fBFRIEND_ON_SOCIAL_MEDIA\&.h\fP"
.br
.ti -1c
.RI "file \fBFRIEND_ON_SOCIAL_MEDIA_INTERFACE\&.h\fP"
.br
.ti -1c
.RI "file \fBSocialMedia\&.cpp\fP"
.br
.ti -1c
.RI "file \fBSocialMedia\&.h\fP"
.br
.ti -1c
.RI "file \fBSocialMediaInterface\&.h\fP"
.br
.in -1c
