.TH "Domain/Game/Actors Directory Reference" 3 "Fri Dec 14 2018" "CPSC 462 - Asteroids" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Domain/Game/Actors Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBActor\&.cpp\fP"
.br
.ti -1c
.RI "file \fBActor\&.h\fP"
.br
.ti -1c
.RI "file \fBActorInterface\&.h\fP"
.br
.ti -1c
.RI "file \fBAlien\&.cpp\fP"
.br
.ti -1c
.RI "file \fBAlien\&.h\fP"
.br
.ti -1c
.RI "file \fBBullet\&.cpp\fP"
.br
.ti -1c
.RI "file \fBBullet\&.h\fP"
.br
.ti -1c
.RI "file \fBGunShip\&.cpp\fP"
.br
.ti -1c
.RI "file \fBGunShip\&.h\fP"
.br
.ti -1c
.RI "file \fBLongRock\&.cpp\fP"
.br
.ti -1c
.RI "file \fBLongRock\&.h\fP"
.br
.ti -1c
.RI "file \fBRect\&.cpp\fP"
.br
.ti -1c
.RI "file \fBRect\&.h\fP"
.br
.ti -1c
.RI "file \fBRock\&.cpp\fP"
.br
.ti -1c
.RI "file \fBRock\&.h\fP"
.br
.ti -1c
.RI "file \fBVector\&.cpp\fP"
.br
.ti -1c
.RI "file \fBVector\&.h\fP"
.br
.in -1c
