.TH "Domain Directory Reference" 3 "Fri Dec 14 2018" "CPSC 462 - Asteroids" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Domain Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBFactory\fP"
.br
.ti -1c
.RI "directory \fBGame\fP"
.br
.ti -1c
.RI "directory \fBNet\fP"
.br
.ti -1c
.RI "directory \fBServer\fP"
.br
.ti -1c
.RI "directory \fBStore\fP"
.br
.in -1c
