.TH "Domain/Net/Authentication Directory Reference" 3 "Fri Dec 14 2018" "CPSC 462 - Asteroids" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Domain/Net/Authentication Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAuthenticationInterface\&.h\fP"
.br
.ti -1c
.RI "file \fBAuthenticator\&.cpp\fP"
.br
.ti -1c
.RI "file \fBAuthenticator\&.h\fP"
.br
.in -1c
