.TH "TechnicalServices/Persistence Directory Reference" 3 "Fri Dec 14 2018" "CPSC 462 - Asteroids" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TechnicalServices/Persistence Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBDatabaser\&.cpp\fP"
.br
.ti -1c
.RI "file \fBDatabaser\&.h\fP"
.br
.ti -1c
.RI "file \fBDatabaserInterface\&.h\fP"
.br
.in -1c
