.TH "TechnicalServices Directory Reference" 3 "Fri Dec 14 2018" "CPSC 462 - Asteroids" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TechnicalServices Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBFinancial\fP"
.br
.ti -1c
.RI "directory \fBPersistence\fP"
.br
.ti -1c
.RI "directory \fBSocial\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBTechnicalServicesFactory\&.cpp\fP"
.br
.ti -1c
.RI "file \fBTechnicalServicesFactory\&.h\fP"
.br
.ti -1c
.RI "file \fBTechnicalServicesFactoryInterface\&.h\fP"
.br
.in -1c
