.TH "Asteroids::TechnicalServices::Persistence" 3 "Fri Dec 14 2018" "CPSC 462 - Asteroids" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Asteroids::TechnicalServices::Persistence \- Package to help with persistence (ie database)  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDatabaser\fP"
.br
.RI "Implementation of \fBDatabaser\fP\&. "
.ti -1c
.RI "class \fBDatabaserInterface\fP"
.br
.RI "The \fBDatabaser\fP interface allows us to connect to and manipulate a database\&. "
.in -1c
.SH "Detailed Description"
.PP 
Package to help with persistence (ie database) 
.SH "Author"
.PP 
Generated automatically by Doxygen for CPSC 462 - Asteroids from the source code\&.
