.TH "Asteroids::Domain::Game::GameHistoryInterface" 3 "Fri Dec 14 2018" "CPSC 462 - Asteroids" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Asteroids::Domain::Game::GameHistoryInterface
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <GameHistoryInterface\&.h>\fP
.PP
Inherited by \fBAsteroids::Domain::Game::GameHistory\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual std::vector< std::shared_ptr< \fBGAME_HISTORY_ENTRY_INTERFACE\fP > > \fBget_history\fP ()=0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 24 of file GameHistoryInterface\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual std::vector<std::shared_ptr<\fBGAME_HISTORY_ENTRY_INTERFACE\fP> > Asteroids::Domain::Game::GameHistoryInterface::get_history ()\fC [pure virtual]\fP"

.PP
Implemented in \fBAsteroids::Domain::Game::GameHistory\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CPSC 462 - Asteroids from the source code\&.
