.TH "Asteroids::UI::ServerTextUI::ServerTextUIInterface" 3 "Fri Dec 14 2018" "CPSC 462 - Asteroids" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Asteroids::UI::ServerTextUI::ServerTextUIInterface \- Main interface to the server's text user interface; Just runs\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ServerTextUIInterface\&.h>\fP
.PP
Inherited by \fBAsteroids::UI::ServerTextUI::ServerTextUI\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBrun\fP ()=0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Main interface to the server's text user interface; Just runs\&. 
.PP
Definition at line 19 of file ServerTextUIInterface\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void Asteroids::UI::ServerTextUI::ServerTextUIInterface::run ()\fC [pure virtual]\fP"

.PP
Implemented in \fBAsteroids::UI::ServerTextUI::ServerTextUI\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CPSC 462 - Asteroids from the source code\&.
