.TH "Asteroids::Domain::Game::Actors::LongRock" 3 "Fri Dec 14 2018" "CPSC 462 - Asteroids" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Asteroids::Domain::Game::Actors::LongRock \- A long rock is an actor that floats within the game; Can be shot by player; Can smash player\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <LongRock\&.h>\fP
.PP
Inherits \fBAsteroids::Domain::Game::Actors::Rock\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLongRock\fP ()"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBinitialize_polygon\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A long rock is an actor that floats within the game; Can be shot by player; Can smash player\&. 
.PP
Definition at line 24 of file LongRock\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Asteroids::Domain::Game::Actors::LongRock::LongRock ()"

.PP
Definition at line 21 of file LongRock\&.cpp\&.
.PP
References initialize_polygon()\&.
.SH "Member Function Documentation"
.PP 
.SS "void Asteroids::Domain::Game::Actors::LongRock::initialize_polygon ()\fC [private]\fP"

.PP
Definition at line 28 of file LongRock\&.cpp\&.
.PP
References ASTEROIDS_GAME_ACTOR_SIZE_FACTOR, and Asteroids::Domain::Game::Actors::Actor::set_polygon()\&.
.PP
Referenced by LongRock()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CPSC 462 - Asteroids from the source code\&.
