.TH "Asteroids::Domain::Server::ServerUpdater" 3 "Fri Dec 14 2018" "CPSC 462 - Asteroids" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Asteroids::Domain::Server::ServerUpdater \- Implements \fBServerUpdaterInterface\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ServerUpdater\&.h>\fP
.PP
Inherits \fBAsteroids::Domain::Server::ServerUpdaterInterface\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBServerUpdater\fP ()"
.br
.ti -1c
.RI "void \fBupdate\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Implements \fBServerUpdaterInterface\fP\&. 
.PP
Definition at line 21 of file ServerUpdater\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Asteroids::Domain::Server::ServerUpdater::ServerUpdater ()"

.PP
Definition at line 23 of file ServerUpdater\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void Asteroids::Domain::Server::ServerUpdater::update ()\fC [virtual]\fP"

.PP
Implements \fBAsteroids::Domain::Server::ServerUpdaterInterface\fP\&.
.PP
Definition at line 29 of file ServerUpdater\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CPSC 462 - Asteroids from the source code\&.
