.TH "Asteroids::UI::ClientTextUI::ClientTextUIInterface" 3 "Fri Dec 14 2018" "CPSC 462 - Asteroids" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Asteroids::UI::ClientTextUI::ClientTextUIInterface \- Interface to the main client text user interface; Just runs, basically\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ClientTextUIInterface\&.h>\fP
.PP
Inherited by \fBAsteroids::UI::ClientTextUI::ClientTextUI\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBrun\fP ()=0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Interface to the main client text user interface; Just runs, basically\&. 
.PP
Definition at line 19 of file ClientTextUIInterface\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void Asteroids::UI::ClientTextUI::ClientTextUIInterface::run ()\fC [pure virtual]\fP"

.PP
Implemented in \fBAsteroids::UI::ClientTextUI::ClientTextUI\fP\&.
.PP
Referenced by main()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CPSC 462 - Asteroids from the source code\&.
