.TH "Asteroids::Domain::Store::Store" 3 "Fri Dec 14 2018" "CPSC 462 - Asteroids" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Asteroids::Domain::Store::Store \- Implementation of \fBStoreInterface\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Store\&.h>\fP
.PP
Inherits \fBAsteroids::Domain::Store::StoreInterface\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStore\fP ()"
.br
.ti -1c
.RI "std::vector< std::shared_ptr< \fBSTORE_ITEM_INTERFACE\fP > > \fBget_available_store_items\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Implementation of \fBStoreInterface\fP\&. 
.PP
Definition at line 24 of file Store\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Asteroids::Domain::Store::Store::Store ()"

.PP
Definition at line 19 of file Store\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "std::vector< std::shared_ptr< \fBSTORE_ITEM_INTERFACE\fP > > Asteroids::Domain::Store::Store::get_available_store_items ()\fC [virtual]\fP"

.PP
\fBTodo\fP
.RS 4
Should 
.PP
Currently returning dummy data; Eventually maybe actually communicate with the server via network 
.RE
.PP

.PP
\fBTodo\fP
.RS 4
Extra lives not actually implemented in the game yet 
.RE
.PP
.PP
\fBTodo\fP
.RS 4
Large bullets not actually implemented in the game yet 
.RE
.PP
.PP
\fBTodo\fP
.RS 4
Rocklike Ship not actually implemented in the game yet 
.RE
.PP

.PP
Implements \fBAsteroids::Domain::Store::StoreInterface\fP\&.
.PP
Definition at line 27 of file Store\&.cpp\&.
.PP
References Asteroids::Domain::Store::Enums::USA\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CPSC 462 - Asteroids from the source code\&.
