.TH "Asteroids::Domain::Factory" 3 "Fri Dec 14 2018" "CPSC 462 - Asteroids" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Asteroids::Domain::Factory \- Hold the main \fBFactory\fP, that generates more specific factories in other packages\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFactory\fP"
.br
.RI "Implementation of \fBFactoryInterface\fP\&. "
.ti -1c
.RI "class \fBFactoryInterface\fP"
.br
.RI "The main \fBFactoryInterface\fP is responsible for generating other factories of subpackages\&. "
.in -1c
.SH "Detailed Description"
.PP 
Hold the main \fBFactory\fP, that generates more specific factories in other packages\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for CPSC 462 - Asteroids from the source code\&.
