.TH "Asteroids::UI::ServerTextUI::Enums" 3 "Fri Dec 14 2018" "CPSC 462 - Asteroids" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Asteroids::UI::ServerTextUI::Enums \- Just a way to keep the \fBEnums\fP in their own namespace so they won't collide with other stuff (perhaps)  

.SH SYNOPSIS
.br
.PP
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBMainMenuChoice\fP { \fBMainMenuChoice::Invalid\fP, \fBMainMenuChoice::ReviewFlaggedUsers\fP, \fBMainMenuChoice::ApplyUpdates\fP, \fBMainMenuChoice::ProcessCreditCardPayment\fP, \fBMainMenuChoice::Shutdown\fP }"
.br
.in -1c
.SH "Detailed Description"
.PP 
Just a way to keep the \fBEnums\fP in their own namespace so they won't collide with other stuff (perhaps) 
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBAsteroids::UI::ServerTextUI::Enums::MainMenuChoice\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIInvalid \fP\fP
.TP
\fB\fIReviewFlaggedUsers \fP\fP
.TP
\fB\fIApplyUpdates \fP\fP
.TP
\fB\fIProcessCreditCardPayment \fP\fP
.TP
\fB\fIShutdown \fP\fP
.PP
Definition at line 18 of file Enums\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CPSC 462 - Asteroids from the source code\&.
