.TH "Asteroids::Domain" 3 "Fri Dec 14 2018" "CPSC 462 - Asteroids" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Asteroids::Domain \- \fBDomain\fP Layer\&.  

.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBFactory\fP"
.br
.RI "Hold the main \fBFactory\fP, that generates more specific factories in other packages\&. "
.ti -1c
.RI " \fBGame\fP"
.br
.RI "The \fBGame\fP package holds things related to playing the game\&. "
.ti -1c
.RI " \fBNet\fP"
.br
.RI "The \fBNet\fP package holds things that help a client communicate with the server\&. "
.ti -1c
.RI " \fBServer\fP"
.br
.RI "The \fBServer\fP namespace holds stuff related to the \fBServer\fP executable\&. "
.ti -1c
.RI " \fBStore\fP"
.br
.RI "The \fBStore\fP namespace holds things related to the \fBStore\fP\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBDomain\fP Layer\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for CPSC 462 - Asteroids from the source code\&.
