.TH "Asteroids::Domain::Net::Messages::Enums" 3 "Fri Dec 14 2018" "CPSC 462 - Asteroids" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Asteroids::Domain::Net::Messages::Enums \- Just a way to keep the \fBEnums\fP in their own namespace so they won't collide with other stuff (perhaps)  

.SH SYNOPSIS
.br
.PP
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBConnectionStatus\fP { \fBConnectionStatus::Unset\fP, \fBConnectionStatus::Successful\fP, \fBConnectionStatus::Failed\fP }
.RI "Result of an attempt by client to connect to the server\&. ""
.br
.in -1c
.SH "Detailed Description"
.PP 
Just a way to keep the \fBEnums\fP in their own namespace so they won't collide with other stuff (perhaps) 
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBAsteroids::Domain::Net::Messages::Enums::ConnectionStatus\fP\fC [strong]\fP"

.PP
Result of an attempt by client to connect to the server\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIUnset \fP\fP
.TP
\fB\fISuccessful \fP\fP
.TP
\fB\fIFailed \fP\fP
.PP
Definition at line 21 of file Enums\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CPSC 462 - Asteroids from the source code\&.
