.TH "Asteroids::Domain::Game::GAME_HISTORY_ENTRY_INTERFACE" 3 "Fri Dec 14 2018" "CPSC 462 - Asteroids" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Asteroids::Domain::Game::GAME_HISTORY_ENTRY_INTERFACE \- Holds one entry of gameplay historical data\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <GAME_HISTORY_ENTRY_INTERFACE\&.h>\fP
.PP
Inherited by \fBAsteroids::Domain::Game::GAME_HISTORY_ENTRY\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual std::string \fBget_date\fP ()=0"
.br
.ti -1c
.RI "virtual std::string \fBget_id\fP ()=0"
.br
.ti -1c
.RI "virtual int \fBget_score\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBset_date\fP (std::string d)=0"
.br
.ti -1c
.RI "virtual void \fBset_id\fP (std::string id)=0"
.br
.ti -1c
.RI "virtual void \fBset_score\fP (int s)=0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Holds one entry of gameplay historical data\&. 
.PP
Definition at line 23 of file GAME_HISTORY_ENTRY_INTERFACE\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual std::string Asteroids::Domain::Game::GAME_HISTORY_ENTRY_INTERFACE::get_date ()\fC [pure virtual]\fP"

.PP
Implemented in \fBAsteroids::Domain::Game::GAME_HISTORY_ENTRY\fP\&.
.SS "virtual std::string Asteroids::Domain::Game::GAME_HISTORY_ENTRY_INTERFACE::get_id ()\fC [pure virtual]\fP"

.PP
Implemented in \fBAsteroids::Domain::Game::GAME_HISTORY_ENTRY\fP\&.
.SS "virtual int Asteroids::Domain::Game::GAME_HISTORY_ENTRY_INTERFACE::get_score ()\fC [pure virtual]\fP"

.PP
Implemented in \fBAsteroids::Domain::Game::GAME_HISTORY_ENTRY\fP\&.
.SS "virtual void Asteroids::Domain::Game::GAME_HISTORY_ENTRY_INTERFACE::set_date (std::string d)\fC [pure virtual]\fP"

.PP
Implemented in \fBAsteroids::Domain::Game::GAME_HISTORY_ENTRY\fP\&.
.SS "virtual void Asteroids::Domain::Game::GAME_HISTORY_ENTRY_INTERFACE::set_id (std::string id)\fC [pure virtual]\fP"

.PP
Implemented in \fBAsteroids::Domain::Game::GAME_HISTORY_ENTRY\fP\&.
.SS "virtual void Asteroids::Domain::Game::GAME_HISTORY_ENTRY_INTERFACE::set_score (int s)\fC [pure virtual]\fP"

.PP
Implemented in \fBAsteroids::Domain::Game::GAME_HISTORY_ENTRY\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CPSC 462 - Asteroids from the source code\&.
