.TH "Asteroids::Domain::Net::Messages" 3 "Fri Dec 14 2018" "CPSC 462 - Asteroids" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Asteroids::Domain::Net::Messages \- The messages namespace just holds all the classes that function more as network data containers than functional classes\&.  

.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBEnums\fP"
.br
.RI "Just a way to keep the \fBEnums\fP in their own namespace so they won't collide with other stuff (perhaps) "
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAUTH_ATTEMPT\fP"
.br
.RI "Just holds one authentication attempt; Is 'sent to server'\&. "
.ti -1c
.RI "class \fBAUTH_STATE\fP"
.br
.RI "Information about the current authentication state\&. "
.in -1c
.SH "Detailed Description"
.PP 
The messages namespace just holds all the classes that function more as network data containers than functional classes\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for CPSC 462 - Asteroids from the source code\&.
