.TH "Asteroids" 3 "Fri Dec 14 2018" "CPSC 462 - Asteroids" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Asteroids \- \fBAsteroids\fP is the main namespace, under which all packages are found\&.  

.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBDomain\fP"
.br
.RI "\fBDomain\fP Layer\&. "
.ti -1c
.RI " \fBTechnicalServices\fP"
.br
.RI "Holds Technical Services\&. "
.ti -1c
.RI " \fBUI\fP"
.br
.RI "The \fBUI\fP namespace holds things related to User Interfaces\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBAsteroids\fP is the main namespace, under which all packages are found\&. 


.PP
\fBTodo\fP
.RS 4
remove me 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for CPSC 462 - Asteroids from the source code\&.
