.TH "Asteroids::TechnicalServices::Social::FRIEND_ON_SOCIAL_MEDIA" 3 "Fri Dec 14 2018" "CPSC 462 - Asteroids" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Asteroids::TechnicalServices::Social::FRIEND_ON_SOCIAL_MEDIA
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <FRIEND_ON_SOCIAL_MEDIA\&.h>\fP
.PP
Inherits \fBAsteroids::TechnicalServices::Social::FRIEND_ON_SOCIAL_MEDIA_INTERFACE\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFRIEND_ON_SOCIAL_MEDIA\fP ()"
.br
.ti -1c
.RI "std::string \fBget_friend_name\fP ()"
.br
.ti -1c
.RI "std::string \fBget_friend_social_media_handle\fP ()"
.br
.ti -1c
.RI "std::string \fBget_social_network_name\fP ()"
.br
.ti -1c
.RI "void \fBset_friend_name\fP (std::string s)"
.br
.ti -1c
.RI "void \fBset_friend_social_media_handle\fP (std::string s)"
.br
.ti -1c
.RI "void \fBset_social_network_name\fP (std::string s)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::string \fB_friend_name\fP"
.br
.ti -1c
.RI "std::string \fB_friend_social_media_handle\fP"
.br
.ti -1c
.RI "std::string \fB_social_network_name\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 28 of file FRIEND_ON_SOCIAL_MEDIA\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Asteroids::TechnicalServices::Social::FRIEND_ON_SOCIAL_MEDIA::FRIEND_ON_SOCIAL_MEDIA ()"

.PP
Definition at line 17 of file FRIEND_ON_SOCIAL_MEDIA\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "std::string Asteroids::TechnicalServices::Social::FRIEND_ON_SOCIAL_MEDIA::get_friend_name ()\fC [virtual]\fP"

.PP
Implements \fBAsteroids::TechnicalServices::Social::FRIEND_ON_SOCIAL_MEDIA_INTERFACE\fP\&.
.PP
Definition at line 44 of file FRIEND_ON_SOCIAL_MEDIA\&.cpp\&.
.PP
References _friend_name\&.
.SS "std::string Asteroids::TechnicalServices::Social::FRIEND_ON_SOCIAL_MEDIA::get_friend_social_media_handle ()\fC [virtual]\fP"

.PP
Implements \fBAsteroids::TechnicalServices::Social::FRIEND_ON_SOCIAL_MEDIA_INTERFACE\fP\&.
.PP
Definition at line 58 of file FRIEND_ON_SOCIAL_MEDIA\&.cpp\&.
.PP
References _friend_social_media_handle\&.
.SS "std::string Asteroids::TechnicalServices::Social::FRIEND_ON_SOCIAL_MEDIA::get_social_network_name ()\fC [virtual]\fP"

.PP
Implements \fBAsteroids::TechnicalServices::Social::FRIEND_ON_SOCIAL_MEDIA_INTERFACE\fP\&.
.PP
Definition at line 30 of file FRIEND_ON_SOCIAL_MEDIA\&.cpp\&.
.PP
References _social_network_name\&.
.SS "void Asteroids::TechnicalServices::Social::FRIEND_ON_SOCIAL_MEDIA::set_friend_name (std::string s)\fC [virtual]\fP"

.PP
Implements \fBAsteroids::TechnicalServices::Social::FRIEND_ON_SOCIAL_MEDIA_INTERFACE\fP\&.
.PP
Definition at line 37 of file FRIEND_ON_SOCIAL_MEDIA\&.cpp\&.
.PP
References _friend_name\&.
.SS "void Asteroids::TechnicalServices::Social::FRIEND_ON_SOCIAL_MEDIA::set_friend_social_media_handle (std::string s)\fC [virtual]\fP"

.PP
Implements \fBAsteroids::TechnicalServices::Social::FRIEND_ON_SOCIAL_MEDIA_INTERFACE\fP\&.
.PP
Definition at line 51 of file FRIEND_ON_SOCIAL_MEDIA\&.cpp\&.
.PP
References _friend_social_media_handle\&.
.SS "void Asteroids::TechnicalServices::Social::FRIEND_ON_SOCIAL_MEDIA::set_social_network_name (std::string s)\fC [virtual]\fP"

.PP
Implements \fBAsteroids::TechnicalServices::Social::FRIEND_ON_SOCIAL_MEDIA_INTERFACE\fP\&.
.PP
Definition at line 23 of file FRIEND_ON_SOCIAL_MEDIA\&.cpp\&.
.PP
References _social_network_name\&.
.SH "Member Data Documentation"
.PP 
.SS "std::string Asteroids::TechnicalServices::Social::FRIEND_ON_SOCIAL_MEDIA::_friend_name\fC [private]\fP"

.PP
Definition at line 54 of file FRIEND_ON_SOCIAL_MEDIA\&.h\&.
.PP
Referenced by get_friend_name(), and set_friend_name()\&.
.SS "std::string Asteroids::TechnicalServices::Social::FRIEND_ON_SOCIAL_MEDIA::_friend_social_media_handle\fC [private]\fP"

.PP
Definition at line 54 of file FRIEND_ON_SOCIAL_MEDIA\&.h\&.
.PP
Referenced by get_friend_social_media_handle(), and set_friend_social_media_handle()\&.
.SS "std::string Asteroids::TechnicalServices::Social::FRIEND_ON_SOCIAL_MEDIA::_social_network_name\fC [private]\fP"

.PP
Definition at line 54 of file FRIEND_ON_SOCIAL_MEDIA\&.h\&.
.PP
Referenced by get_social_network_name(), and set_social_network_name()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CPSC 462 - Asteroids from the source code\&.
