.TH "Asteroids::TechnicalServices::Social::SocialMedia" 3 "Fri Dec 14 2018" "CPSC 462 - Asteroids" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Asteroids::TechnicalServices::Social::SocialMedia
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SocialMedia\&.h>\fP
.PP
Inherits \fBAsteroids::TechnicalServices::Social::SocialMediaInterface\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSocialMedia\fP ()"
.br
.ti -1c
.RI "std::vector< std::shared_ptr< \fBFRIEND_ON_SOCIAL_MEDIA_INTERFACE\fP > > \fBget_game_friends_on_social_media\fP ()"
.br
.ti -1c
.RI "bool \fBshare_game_history_entry\fP (std::string date, int score)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 25 of file SocialMedia\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Asteroids::TechnicalServices::Social::SocialMedia::SocialMedia ()"

.PP
Definition at line 25 of file SocialMedia\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "std::vector< std::shared_ptr< \fBFRIEND_ON_SOCIAL_MEDIA_INTERFACE\fP > > Asteroids::TechnicalServices::Social::SocialMedia::get_game_friends_on_social_media ()\fC [virtual]\fP"

.PP
Implements \fBAsteroids::TechnicalServices::Social::SocialMediaInterface\fP\&.
.PP
Definition at line 48 of file SocialMedia\&.cpp\&.
.SS "bool Asteroids::TechnicalServices::Social::SocialMedia::share_game_history_entry (std::string date, int score)\fC [virtual]\fP"

.PP
\fBTodo\fP
.RS 4
Emitting to stdout instead of actually doing anything \&.\&.\&. for now 
.RE
.PP

.PP
Implements \fBAsteroids::TechnicalServices::Social::SocialMediaInterface\fP\&.
.PP
Definition at line 31 of file SocialMedia\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CPSC 462 - Asteroids from the source code\&.
