.TH "Asteroids::TechnicalServices" 3 "Fri Dec 14 2018" "CPSC 462 - Asteroids" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Asteroids::TechnicalServices \- Holds Technical Services\&.  

.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBFinancial\fP"
.br
.RI "Package to help with external \fBFinancial\fP services\&. "
.ti -1c
.RI " \fBPersistence\fP"
.br
.RI "Package to help with persistence (ie database) "
.ti -1c
.RI " \fBSocial\fP"
.br
.RI "Package to hold social media related stuffs\&. "
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTechnicalServicesFactory\fP"
.br
.RI "Implementation of \fBTechnicalServicesFactoryInterface\fP\&. "
.ti -1c
.RI "class \fBTechnicalServicesFactoryInterface\fP"
.br
.RI "Creates objects that belong to the \fBTechnicalServices\fP package\&. "
.in -1c
.SH "Detailed Description"
.PP 
Holds Technical Services\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for CPSC 462 - Asteroids from the source code\&.
