.TH "Asteroids::Domain::Game::GameHistory" 3 "Fri Dec 14 2018" "CPSC 462 - Asteroids" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Asteroids::Domain::Game::GameHistory
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <GameHistory\&.h>\fP
.PP
Inherits \fBAsteroids::Domain::Game::GameHistoryInterface\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGameHistory\fP ()"
.br
.ti -1c
.RI "std::vector< std::shared_ptr< \fBGAME_HISTORY_ENTRY_INTERFACE\fP > > \fBget_history\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 26 of file GameHistory\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Asteroids::Domain::Game::GameHistory::GameHistory ()"

.PP
Definition at line 19 of file GameHistory\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "std::vector< std::shared_ptr< \fBGAME_HISTORY_ENTRY_INTERFACE\fP > > Asteroids::Domain::Game::GameHistory::get_history ()\fC [virtual]\fP"

.PP
\fBTodo\fP
.RS 4
Still returning dummy data 
.RE
.PP

.PP
Implements \fBAsteroids::Domain::Game::GameHistoryInterface\fP\&.
.PP
Definition at line 25 of file GameHistory\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CPSC 462 - Asteroids from the source code\&.
