.TH "Asteroids::Domain::Store" 3 "Fri Dec 14 2018" "CPSC 462 - Asteroids" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Asteroids::Domain::Store \- The \fBStore\fP namespace holds things related to the \fBStore\fP\&.  

.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBEnums\fP"
.br
.RI "Just a way to keep the \fBEnums\fP in their own namespace so they won't collide with other stuff (perhaps) "
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPAYMENT_RESULT_DETAILS\fP"
.br
.RI "Implementation of PATMENT_RESULTS_DETAILS_INTERFACE\&. "
.ti -1c
.RI "class \fBPAYMENT_RESULT_DETAILS_INTERFACE\fP"
.br
.RI "Results of an attempt to authorize payment\&. "
.ti -1c
.RI "class \fBPaymentHelper\fP"
.br
.RI "Implementation of \fBPaymentHelperInterface\fP\&. "
.ti -1c
.RI "class \fBPaymentHelperInterface\fP"
.br
.RI "A class that lets you attempt to make payments\&. "
.ti -1c
.RI "class \fBPOWERUP_ADDED_INFO\fP"
.br
.RI "Implementation of \fBPOWERUP_ADDED_INFO_INTERFACE\fP\&. "
.ti -1c
.RI "class \fBPOWERUP_ADDED_INFO_INTERFACE\fP"
.br
.RI "Information what powerup was just added to your account\&. "
.ti -1c
.RI "class \fBStore\fP"
.br
.RI "Implementation of \fBStoreInterface\fP\&. "
.ti -1c
.RI "class \fBSTORE_ITEM\fP"
.br
.RI "Implementation of \fBSTORE_ITEM_INTERFACE\fP\&. "
.ti -1c
.RI "class \fBSTORE_ITEM_INTERFACE\fP"
.br
.RI "Interface for one item available for purchase, inside the \fBStore\fP\&. "
.ti -1c
.RI "class \fBStoreFactory\fP"
.br
.RI "Implementation of \fBStoreFactoryInterface\fP\&. "
.ti -1c
.RI "class \fBStoreFactoryInterface\fP"
.br
.RI "Creates things inside the \fBStore\fP package\&. "
.ti -1c
.RI "class \fBStoreInterface\fP"
.br
.RI "The \fBStore\fP interface lets you poll things that \&.\&.\&. a store would tell you\&.\&.\&. such as what items are available for sale\&. "
.in -1c
.SH "Detailed Description"
.PP 
The \fBStore\fP namespace holds things related to the \fBStore\fP\&. 

So far this is just things the Client executable would use 
.SH "Author"
.PP 
Generated automatically by Doxygen for CPSC 462 - Asteroids from the source code\&.
