.TH "Asteroids::TechnicalServices::Social" 3 "Fri Dec 14 2018" "CPSC 462 - Asteroids" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Asteroids::TechnicalServices::Social \- Package to hold social media related stuffs\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFRIEND_ON_SOCIAL_MEDIA\fP"
.br
.ti -1c
.RI "class \fBFRIEND_ON_SOCIAL_MEDIA_INTERFACE\fP"
.br
.ti -1c
.RI "class \fBSocialMedia\fP"
.br
.ti -1c
.RI "class \fBSocialMediaInterface\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Package to hold social media related stuffs\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for CPSC 462 - Asteroids from the source code\&.
