.TH "Asteroids::Domain::Net::Authentication" 3 "Fri Dec 14 2018" "CPSC 462 - Asteroids" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Asteroids::Domain::Net::Authentication \- The \fBAuthentication\fP namespace just holds stuff related to authenticating the client with the server\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAuthenticationInterface\fP"
.br
.RI "Main interface for client to authenticate with server\&. "
.ti -1c
.RI "class \fBAuthenticator\fP"
.br
.RI "Implementation of \fBAuthenticationInterface\fP\&. "
.in -1c
.SH "Detailed Description"
.PP 
The \fBAuthentication\fP namespace just holds stuff related to authenticating the client with the server\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for CPSC 462 - Asteroids from the source code\&.
