.TH "Asteroids::TechnicalServices::Financial::FinancialServices" 3 "Fri Dec 14 2018" "CPSC 462 - Asteroids" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Asteroids::TechnicalServices::Financial::FinancialServices \- Implementation of \fBFinancialServicesInterface\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <FinancialServices\&.h>\fP
.PP
Inherits \fBAsteroids::TechnicalServices::Financial::FinancialServicesInterface\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFinancialServices\fP ()"
.br
.ti -1c
.RI "bool \fBauthorizePayment\fP (std::string cc_number, std::string cc_expiration, std::string cc_security_code)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Implementation of \fBFinancialServicesInterface\fP\&. 
.PP
Definition at line 20 of file FinancialServices\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Asteroids::TechnicalServices::Financial::FinancialServices::FinancialServices ()"

.PP
Definition at line 17 of file FinancialServices\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "bool Asteroids::TechnicalServices::Financial::FinancialServices::authorizePayment (std::string cc_number, std::string cc_expiration, std::string cc_security_code)\fC [virtual]\fP"

.PP
Implements \fBAsteroids::TechnicalServices::Financial::FinancialServicesInterface\fP\&.
.PP
Definition at line 23 of file FinancialServices\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CPSC 462 - Asteroids from the source code\&.
