.TH "Asteroids::TechnicalServices::Financial" 3 "Fri Dec 14 2018" "CPSC 462 - Asteroids" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Asteroids::TechnicalServices::Financial \- Package to help with external \fBFinancial\fP services\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCreditCardProcessorInterface\fP"
.br
.ti -1c
.RI "class \fBFinancialServices\fP"
.br
.RI "Implementation of \fBFinancialServicesInterface\fP\&. "
.ti -1c
.RI "class \fBFinancialServicesInterface\fP"
.br
.RI "Provides an interface to external financial services, such as external banking systems\&. "
.ti -1c
.RI "class \fBMastercardProcessor\fP"
.br
.ti -1c
.RI "class \fBVisaProcessor\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Package to help with external \fBFinancial\fP services\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for CPSC 462 - Asteroids from the source code\&.
