.TH "Asteroids::Domain::Server::HACCS_REPORT_ACTIVITY_INTERFACE" 3 "Fri Dec 14 2018" "CPSC 462 - Asteroids" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Asteroids::Domain::Server::HACCS_REPORT_ACTIVITY_INTERFACE \- Data structure class that contains a description of one suspicious activity\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <HACCS_REPORT_ACTIVITY_INTERFACE\&.h>\fP
.PP
Inherited by \fBAsteroids::Domain::Server::HACCS_REPORT_ACTIVITY\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual std::string \fBget_what\fP ()=0"
.br
.ti -1c
.RI "virtual std::string \fBget_when\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBreset\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBset_what\fP (std::string what)=0"
.br
.ti -1c
.RI "virtual void \fBset_when\fP (std::string when)=0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Data structure class that contains a description of one suspicious activity\&. 
.PP
Definition at line 23 of file HACCS_REPORT_ACTIVITY_INTERFACE\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual std::string Asteroids::Domain::Server::HACCS_REPORT_ACTIVITY_INTERFACE::get_what ()\fC [pure virtual]\fP"

.PP
Implemented in \fBAsteroids::Domain::Server::HACCS_REPORT_ACTIVITY\fP\&.
.SS "virtual std::string Asteroids::Domain::Server::HACCS_REPORT_ACTIVITY_INTERFACE::get_when ()\fC [pure virtual]\fP"

.PP
Implemented in \fBAsteroids::Domain::Server::HACCS_REPORT_ACTIVITY\fP\&.
.SS "virtual void Asteroids::Domain::Server::HACCS_REPORT_ACTIVITY_INTERFACE::reset ()\fC [pure virtual]\fP"

.PP
Implemented in \fBAsteroids::Domain::Server::HACCS_REPORT_ACTIVITY\fP\&.
.SS "virtual void Asteroids::Domain::Server::HACCS_REPORT_ACTIVITY_INTERFACE::set_what (std::string what)\fC [pure virtual]\fP"

.PP
Implemented in \fBAsteroids::Domain::Server::HACCS_REPORT_ACTIVITY\fP\&.
.SS "virtual void Asteroids::Domain::Server::HACCS_REPORT_ACTIVITY_INTERFACE::set_when (std::string when)\fC [pure virtual]\fP"

.PP
Implemented in \fBAsteroids::Domain::Server::HACCS_REPORT_ACTIVITY\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CPSC 462 - Asteroids from the source code\&.
