.TH "Asteroids::UI::ClientTextUI::Enums" 3 "Fri Dec 14 2018" "CPSC 462 - Asteroids" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Asteroids::UI::ClientTextUI::Enums \- Just a way to keep the \fBEnums\fP in their own namespace so they won't collide with other stuff (perhaps)  

.SH SYNOPSIS
.br
.PP
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBMainMenuChoice\fP { \fBMainMenuChoice::PlayGame\fP, \fBMainMenuChoice::ReviewGameHistory\fP, \fBMainMenuChoice::FindFriendsOnSocialMedia\fP, \fBMainMenuChoice::PowerUpStore\fP, \fBMainMenuChoice::Quit\fP, \fBMainMenuChoice::Invalid\fP }"
.br
.in -1c
.SH "Detailed Description"
.PP 
Just a way to keep the \fBEnums\fP in their own namespace so they won't collide with other stuff (perhaps) 
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBAsteroids::UI::ClientTextUI::Enums::MainMenuChoice\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIPlayGame \fP\fP
.TP
\fB\fIReviewGameHistory \fP\fP
.TP
\fB\fIFindFriendsOnSocialMedia \fP\fP
.TP
\fB\fIPowerUpStore \fP\fP
.TP
\fB\fIQuit \fP\fP
.TP
\fB\fIInvalid \fP\fP
.PP
Definition at line 18 of file Enums\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CPSC 462 - Asteroids from the source code\&.
