.TH "Asteroids::UI::ClientTextUI" 3 "Fri Dec 14 2018" "CPSC 462 - Asteroids" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Asteroids::UI::ClientTextUI \- Holds things related to the client text user interface\&.  

.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBEnums\fP"
.br
.RI "Just a way to keep the \fBEnums\fP in their own namespace so they won't collide with other stuff (perhaps) "
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBClientTextUI\fP"
.br
.RI "Implementation of \fBClientTextUIInterface\fP\&. "
.ti -1c
.RI "class \fBClientTextUIInterface\fP"
.br
.RI "Interface to the main client text user interface; Just runs, basically\&. "
.ti -1c
.RI "class \fBDisplayGrid\fP"
.br
.RI "Class to help translate and render actors and stuff from the virtual game board, to actual ASCII graphics that can be seen\&. "
.ti -1c
.RI "class \fBInput\fP"
.br
.RI "Thank you very much: https://stackoverflow.com/questions/448944/c-non-blocking-keyboard-input\&. "
.in -1c
.SH "Detailed Description"
.PP 
Holds things related to the client text user interface\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for CPSC 462 - Asteroids from the source code\&.
