.TH "Asteroids::Domain::Store::Enums" 3 "Fri Dec 14 2018" "CPSC 462 - Asteroids" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Asteroids::Domain::Store::Enums \- Just a way to keep the \fBEnums\fP in their own namespace so they won't collide with other stuff (perhaps)  

.SH SYNOPSIS
.br
.PP
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBCurrencyType\fP { \fBCurrencyType::Undefined\fP, \fBCurrencyType::USA\fP }"
.br
.ti -1c
.RI "enum \fBPaymentMethod\fP { \fBPaymentMethod::Undefined\fP, \fBPaymentMethod::AccountBalance\fP, \fBPaymentMethod::CreditCard\fP, \fBPaymentMethod::Paypal\fP, \fBPaymentMethod::Bitcoin\fP, \fBPaymentMethod::Blood\fP }"
.br
.in -1c
.SH "Detailed Description"
.PP 
Just a way to keep the \fBEnums\fP in their own namespace so they won't collide with other stuff (perhaps) 
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBAsteroids::Domain::Store::Enums::CurrencyType\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIUndefined \fP\fP
.TP
\fB\fIUSA \fP\fP
.PP
Definition at line 18 of file Enums\&.h\&.
.SS "enum \fBAsteroids::Domain::Store::Enums::PaymentMethod\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIUndefined \fP\fP
.TP
\fB\fIAccountBalance \fP\fP
.TP
\fB\fICreditCard \fP\fP
.TP
\fB\fIPaypal \fP\fP
.TP
\fB\fIBitcoin \fP\fP
.TP
\fB\fIBlood \fP\fP
.PP
Definition at line 26 of file Enums\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CPSC 462 - Asteroids from the source code\&.
