.TH "Asteroids::TechnicalServices::Social::FRIEND_ON_SOCIAL_MEDIA_INTERFACE" 3 "Fri Dec 14 2018" "CPSC 462 - Asteroids" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Asteroids::TechnicalServices::Social::FRIEND_ON_SOCIAL_MEDIA_INTERFACE
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <FRIEND_ON_SOCIAL_MEDIA_INTERFACE\&.h>\fP
.PP
Inherited by \fBAsteroids::TechnicalServices::Social::FRIEND_ON_SOCIAL_MEDIA\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual std::string \fBget_friend_name\fP ()=0"
.br
.ti -1c
.RI "virtual std::string \fBget_friend_social_media_handle\fP ()=0"
.br
.ti -1c
.RI "virtual std::string \fBget_social_network_name\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBset_friend_name\fP (std::string s)=0"
.br
.ti -1c
.RI "virtual void \fBset_friend_social_media_handle\fP (std::string s)=0"
.br
.ti -1c
.RI "virtual void \fBset_social_network_name\fP (std::string s)=0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 24 of file FRIEND_ON_SOCIAL_MEDIA_INTERFACE\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual std::string Asteroids::TechnicalServices::Social::FRIEND_ON_SOCIAL_MEDIA_INTERFACE::get_friend_name ()\fC [pure virtual]\fP"

.PP
Implemented in \fBAsteroids::TechnicalServices::Social::FRIEND_ON_SOCIAL_MEDIA\fP\&.
.SS "virtual std::string Asteroids::TechnicalServices::Social::FRIEND_ON_SOCIAL_MEDIA_INTERFACE::get_friend_social_media_handle ()\fC [pure virtual]\fP"

.PP
Implemented in \fBAsteroids::TechnicalServices::Social::FRIEND_ON_SOCIAL_MEDIA\fP\&.
.SS "virtual std::string Asteroids::TechnicalServices::Social::FRIEND_ON_SOCIAL_MEDIA_INTERFACE::get_social_network_name ()\fC [pure virtual]\fP"

.PP
Implemented in \fBAsteroids::TechnicalServices::Social::FRIEND_ON_SOCIAL_MEDIA\fP\&.
.SS "virtual void Asteroids::TechnicalServices::Social::FRIEND_ON_SOCIAL_MEDIA_INTERFACE::set_friend_name (std::string s)\fC [pure virtual]\fP"

.PP
Implemented in \fBAsteroids::TechnicalServices::Social::FRIEND_ON_SOCIAL_MEDIA\fP\&.
.SS "virtual void Asteroids::TechnicalServices::Social::FRIEND_ON_SOCIAL_MEDIA_INTERFACE::set_friend_social_media_handle (std::string s)\fC [pure virtual]\fP"

.PP
Implemented in \fBAsteroids::TechnicalServices::Social::FRIEND_ON_SOCIAL_MEDIA\fP\&.
.SS "virtual void Asteroids::TechnicalServices::Social::FRIEND_ON_SOCIAL_MEDIA_INTERFACE::set_social_network_name (std::string s)\fC [pure virtual]\fP"

.PP
Implemented in \fBAsteroids::TechnicalServices::Social::FRIEND_ON_SOCIAL_MEDIA\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CPSC 462 - Asteroids from the source code\&.
