.TH "boost::shared_ptr< T >" 3 "Fri Dec 14 2018" "CPSC 462 - Asteroids" \" -*- nroff -*-
.ad l
.nh
.SH NAME
boost::shared_ptr< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <doxygen_dummy\&.h>\fP
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "T * \fBdummy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class T>
.br
class boost::shared_ptr< T >"

.PP
Definition at line 2 of file doxygen_dummy\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "template<class T > T* \fBboost::shared_ptr\fP< T >::dummy\fC [private]\fP"

.PP
Definition at line 2 of file doxygen_dummy\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CPSC 462 - Asteroids from the source code\&.
