.TH "UI/ClientTextUI/ClientTextUIInterface.h" 3 "Fri Dec 14 2018" "CPSC 462 - Asteroids" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UI/ClientTextUI/ClientTextUIInterface.h
.SH SYNOPSIS
.br
.PP
\fC#include 'Asteroids/ForwardDeclarations\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAsteroids::UI::ClientTextUI::ClientTextUIInterface\fP"
.br
.RI "Interface to the main client text user interface; Just runs, basically\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBAsteroids\fP"
.br
.RI "\fBAsteroids\fP is the main namespace, under which all packages are found\&. "
.ti -1c
.RI " \fBAsteroids::UI\fP"
.br
.RI "The \fBUI\fP namespace holds things related to User Interfaces\&. "
.ti -1c
.RI " \fBAsteroids::UI::ClientTextUI\fP"
.br
.RI "Holds things related to the client text user interface\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CPSC 462 - Asteroids from the source code\&.
