.TH "UI/ClientTextUI/ClientTextUI.cpp" 3 "Fri Dec 14 2018" "CPSC 462 - Asteroids" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UI/ClientTextUI/ClientTextUI.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Asteroids/UI/ClientTextUI/ClientTextUI\&.h'\fP
.br
\fC#include 'Asteroids/UI/ClientTextUI/Input\&.h'\fP
.br
\fC#include 'Asteroids/UI/ClientTextUI/DisplayGrid\&.h'\fP
.br
\fC#include 'Asteroids/Domain/Factory/FactoryInterface\&.h'\fP
.br
\fC#include 'Asteroids/Domain/Game/GameFactoryInterface\&.h'\fP
.br
\fC#include 'Asteroids/Domain/Game/GameInterface\&.h'\fP
.br
\fC#include 'Asteroids/Domain/Game/Actors/ActorInterface\&.h'\fP
.br
\fC#include 'Asteroids/Domain/Game/GameHistory\&.h'\fP
.br
\fC#include 'Asteroids/Domain/Game/GAME_HISTORY_ENTRY_INTERFACE\&.h'\fP
.br
\fC#include 'Asteroids/Domain/Net/NetFactoryInterface\&.h'\fP
.br
\fC#include 'Asteroids/Domain/Net/ClientServerCommunicatorInterface\&.h'\fP
.br
\fC#include 'Asteroids/Domain/Net/Authentication/AuthenticationInterface\&.h'\fP
.br
\fC#include 'Asteroids/Domain/Net/Messages/AUTH_ATTEMPT\&.h'\fP
.br
\fC#include 'Asteroids/Domain/Net/Messages/AUTH_STATE\&.h'\fP
.br
\fC#include 'Asteroids/Domain/Store/StoreFactoryInterface\&.h'\fP
.br
\fC#include 'Asteroids/Domain/Store/StoreInterface\&.h'\fP
.br
\fC#include 'Asteroids/Domain/Store/STORE_ITEM_INTERFACE\&.h'\fP
.br
\fC#include 'Asteroids/Domain/Store/PaymentHelperInterface\&.h'\fP
.br
\fC#include 'Asteroids/Domain/Store/PAYMENT_RESULT_DETAILS_INTERFACE\&.h'\fP
.br
\fC#include 'Asteroids/Domain/Store/POWERUP_ADDED_INFO_INTERFACE\&.h'\fP
.br
\fC#include 'Asteroids/TechnicalServices/TechnicalServicesFactoryInterface\&.h'\fP
.br
\fC#include 'Asteroids/TechnicalServices/Social/SocialMediaInterface\&.h'\fP
.br
\fC#include 'Asteroids/TechnicalServices/Social/FRIEND_ON_SOCIAL_MEDIA_INTERFACE\&.h'\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include <iostream>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBAsteroids\fP"
.br
.RI "\fBAsteroids\fP is the main namespace, under which all packages are found\&. "
.ti -1c
.RI " \fBAsteroids::UI\fP"
.br
.RI "The \fBUI\fP namespace holds things related to User Interfaces\&. "
.ti -1c
.RI " \fBAsteroids::UI::ClientTextUI\fP"
.br
.RI "Holds things related to the client text user interface\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CPSC 462 - Asteroids from the source code\&.
