.TH "UI/ClientTextUI/Defines.h" 3 "Fri Dec 14 2018" "CPSC 462 - Asteroids" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UI/ClientTextUI/Defines.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBASTEROIDS_UI_TEXTUI_DISPLAYGRID_HEIGHT\fP   30"
.br
.ti -1c
.RI "#define \fBASTEROIDS_UI_TEXTUI_DISPLAYGRID_WIDTH\fP   120"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ASTEROIDS_UI_TEXTUI_DISPLAYGRID_HEIGHT   30"

.PP
Definition at line 7 of file Defines\&.h\&.
.PP
Referenced by Asteroids::UI::ClientTextUI::ClientTextUI::initialize_display_grid()\&.
.SS "#define ASTEROIDS_UI_TEXTUI_DISPLAYGRID_WIDTH   120"

.PP
Definition at line 6 of file Defines\&.h\&.
.PP
Referenced by Asteroids::UI::ClientTextUI::ClientTextUI::initialize_display_grid()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CPSC 462 - Asteroids from the source code\&.
