.TH "Domain/Game/Game.cpp" 3 "Fri Dec 14 2018" "CPSC 462 - Asteroids" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Domain/Game/Game.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Asteroids/Domain/Game/Game\&.h'\fP
.br
\fC#include 'Asteroids/Domain/Factory/Factory\&.h'\fP
.br
\fC#include 'Asteroids/Domain/Game/Defines\&.h'\fP
.br
\fC#include 'Asteroids/Domain/Game/Randomer\&.h'\fP
.br
\fC#include 'Asteroids/Domain/Game/Actors/GunShip\&.h'\fP
.br
\fC#include 'Asteroids/Domain/Game/Actors/Bullet\&.h'\fP
.br
\fC#include 'Asteroids/Domain/Game/Actors/Rock\&.h'\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <chrono>\fP
.br
\fC#include <thread>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBAsteroids\fP"
.br
.RI "\fBAsteroids\fP is the main namespace, under which all packages are found\&. "
.ti -1c
.RI " \fBAsteroids::Domain\fP"
.br
.RI "\fBDomain\fP Layer\&. "
.ti -1c
.RI " \fBAsteroids::Domain::Game\fP"
.br
.RI "The \fBGame\fP package holds things related to playing the game\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CPSC 462 - Asteroids from the source code\&.
