.TH "main-console-client.cpp" 3 "Fri Dec 14 2018" "CPSC 462 - Asteroids" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main-console-client.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Asteroids/Domain/Factory/Factory\&.h'\fP
.br
\fC#include 'Asteroids/UI/UIFactoryInterface\&.h'\fP
.br
\fC#include 'Asteroids/UI/ClientTextUI/ClientTextUIInterface\&.h'\fP
.br
\fC#include <iostream>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main ()"

.PP
Definition at line 19 of file main\-console\-client\&.cpp\&.
.PP
References Asteroids::UI::UIFactoryInterface::createClientTextUI(), and Asteroids::UI::ClientTextUI::ClientTextUIInterface::run()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CPSC 462 - Asteroids from the source code\&.
