.TH "main-server.cpp" 3 "Fri Dec 14 2018" "CPSC 462 - Asteroids" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main-server.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Asteroids/Domain/Factory/Factory\&.h'\fP
.br
\fC#include 'Asteroids/UI/UIFactoryInterface\&.h'\fP
.br
\fC#include 'Asteroids/UI/ServerTextUI/ServerTextUIInterface\&.h'\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <chrono>\fP
.br
\fC#include <thread>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main ()"

.PP
Definition at line 22 of file main\-server\&.cpp\&.
.PP
References Asteroids::UI::UIFactoryInterface::createServerTextUI()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CPSC 462 - Asteroids from the source code\&.
