.TH "TechnicalServices/Financial/VisaProcessor.h" 3 "Fri Dec 14 2018" "CPSC 462 - Asteroids" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TechnicalServices/Financial/VisaProcessor.h
.SH SYNOPSIS
.br
.PP
\fC#include 'Asteroids/ForwardDeclarations\&.h'\fP
.br
\fC#include 'Asteroids/TechnicalServices/Financial/CreditCardProcessorInterface\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAsteroids::TechnicalServices::Financial::VisaProcessor\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBAsteroids\fP"
.br
.RI "\fBAsteroids\fP is the main namespace, under which all packages are found\&. "
.ti -1c
.RI " \fBAsteroids::TechnicalServices\fP"
.br
.RI "Holds Technical Services\&. "
.ti -1c
.RI " \fBAsteroids::TechnicalServices::Financial\fP"
.br
.RI "Package to help with external \fBFinancial\fP services\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CPSC 462 - Asteroids from the source code\&.
