#ifndef ASTEROIDS_GAME_DEFINES_H
#define ASTEROIDS_GAME_DEFINES_H


//	Board dimensions
#define ASTEROIDS_GAME_BOARD_WIDTH			3000
#define ASTEROIDS_GAME_BOARD_HEIGHT			720
#define ASTEROIDS_GAME_ACTOR_SIZE_FACTOR	25


//	Current ticks-per-second setting
#define ASTEROIDS_GAME_TICKS_PER_SECOND				1000000
#define ASTEROIDS_GAME_TARGET_FRAMES_PER_SECOND		30


//	Maximum velocity per component
///	@todo Maybe remove these for static members!?
#define ASTEROIDS_GAME_VELOCITY_INPUT_TICKS_FACTOR					0.00000000005
#define ASTEROIDS_GAME_VELOCITY_DAMPENING_TICKS_FACTOR				0.99999999
#define ASTEROIDS_GAME_VELOCITY_ROTAIONAL_DAMPENING_TICKS_FACTOR	0.99999
#define ASTEROIDS_GAME_VELOCITY_MAX									5
#define ASTEROIDS_GAME_VELOCITY_ROTATIONAL_MAX						0.000001


//
#define ASTEROIDS_GAME_BULLET_DEFAULT_SPEED							0.00001
#define ASTEROIDS_GAME_GUNSHIP_BULLET_SPEED							0.001
//
#define ASTEROIDS_GAME_BULLET_LIFETIME_TICKS						3 * ASTEROIDS_GAME_TICKS_PER_SECOND


//
#define ASTEROIDS_GAME_ROCKS_POINTS									10
#define ASTEROIDS_GAME_ROCKS_PER_LEVEL								10
#define ASTEROIDS_GAME_ROCKS_INITIAL_VELOCITY_STRENGTH				0.0001




#endif
